//! Refactor mode as a recording site.
//!
//! Protects `docs/guarantees/lineage/a-refactor-records-what-it-moved.md`.
//!
//! Refactor mode is a machine for destroying textual continuity while
//! guaranteeing semantic identity: pin a baseline, restructure the document
//! freely, and `compare_outputs` proves the generated bytes unchanged — while
//! blame afterwards says every line is new. That is the one case where git's
//! line-based correlation is not merely weak but wrong, and this product
//! creates it deliberately.
//!
//! The mechanism costs almost nothing, because the work is already done:
//! **the outputs are proven identical, which makes them a join key.**

use std::path::PathBuf;

use hickory_cli::ExecutorChoice;
use hickory_cli::serve::{ServeOptions, prepare};
use serde_json::{Value, json};

const BEFORE: &str = r##"<?xml version="1.0" encoding="UTF-8"?>
<hick:doc xmlns:hick="http://www.hickorydocs.com/1.0" weave="none">
# Demo

<hick:file path="greet.rs">fn greet() { println!("hello"); }
</hick:file>
</hick:doc>
"##;

/// The same outputs, from a document restructured so every line moved: the
/// body now comes from a copy block pasted into the file.
const AFTER: &str = r##"<?xml version="1.0" encoding="UTF-8"?>
<hick:doc xmlns:hick="http://www.hickorydocs.com/1.0" weave="none">
# Demo, restructured

Some prose that did not exist before, so every byte after it has moved.

<hick:copy id="greet">fn greet() { println!("hello"); }
</hick:copy>
<hick:file path="greet.rs"><hick:paste select="#greet" /></hick:file>
</hick:doc>
"##;

struct Session {
    base: String,
    doc_id: String,
    root: PathBuf,
    _dir: tempfile::TempDir,
    _state: tempfile::TempDir,
}

async fn start(continuity: bool) -> Session {
    let dir = tempfile::tempdir().unwrap();
    let state_dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("demo.hick"), BEFORE).unwrap();
    let root = dir.path().canonicalize().unwrap();

    // The switch lives in the per-user state directory, keyed by the
    // project's canonical path — not in the browser, because the things that
    // WRITE a journal cannot read localStorage.
    unsafe { std::env::set_var("HICKORY_STATE_DIR", state_dir.path()) };
    let store = hickory_workspace::WorkspaceStore::under(state_dir.path(), &root).unwrap();
    assert!(!store.continuity(), "continuity is off by default");
    if continuity {
        store.set_continuity(true).unwrap();
    }

    let prepared = prepare(ServeOptions {
        target: root.join("demo.hick"),
        port: 0,
        params: Vec::new(),
        executor: ExecutorChoice::Local,
        key_store_path: None,
        ui_settings_path: None,
    })
    .await
    .expect("session prepares");

    let doc_id = prepared.state.index.sole().expect("one document").0;
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let port = listener.local_addr().unwrap().port();
    tokio::spawn(async move {
        axum::serve(listener, prepared.router).await.unwrap();
    });

    Session {
        base: format!("http://127.0.0.1:{port}"),
        doc_id,
        root,
        _dir: dir,
        _state: state_dir,
    }
}

async fn post(session: &Session, path: &str, body: Value) -> Value {
    reqwest::Client::new()
        .post(format!("{}{path}", session.base))
        .json(&body)
        .send()
        .await
        .unwrap()
        .json()
        .await
        .unwrap_or(Value::Null)
}

fn journal(session: &Session) -> Vec<Value> {
    let path = session.root.join(".hick-journal/correspondences.jsonl");
    let Ok(body) = std::fs::read_to_string(path) else {
        return Vec::new();
    };
    body.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| serde_json::from_str(l).unwrap())
        .collect()
}

#[tokio::test]
async fn a_restructure_that_moved_every_line_records_what_moved() {
    let session = start(true).await;
    let id = session.doc_id.clone();

    let begun = post(
        &session,
        &format!("/api/docs/{id}/refactor/begin"),
        json!({}),
    )
    .await;
    assert_eq!(begun["active"], json!(true));

    // Restructure. The outputs are unchanged; every byte of the document
    // moved.
    std::fs::write(session.root.join("demo.hick"), AFTER).unwrap();

    let ended = post(&session, &format!("/api/docs/{id}/refactor/end"), json!({})).await;
    assert_eq!(ended["active"], json!(false));
    assert!(
        ended["recorded"].as_u64().unwrap_or(0) > 0,
        "nothing recorded: {ended}"
    );

    let entries = journal(&session);
    assert!(!entries.is_empty(), "the journal is empty");
    for entry in &entries {
        // Joined through outputs proven identical: the strongest precision
        // any site here produces.
        assert_eq!(entry["precision"], json!("byte"), "{entry}");
        assert_eq!(entry["site"], json!("refactor"), "{entry}");
        // Both ends are the working tree, which is above the floor by
        // definition.
        assert_eq!(entry["provisional"], json!(true), "{entry}");
        // And they say a span MOVED — "this span is itself" is not a fact
        // worth a line in a record.
        assert_ne!(entry["from"]["span"], entry["to"]["span"], "{entry}");
    }
}

#[tokio::test]
async fn a_restructure_that_changed_the_outputs_records_nothing() {
    // Nothing was preserved, so there is nothing to say two spans are the
    // same thing — and recording it anyway would put a false fact into a
    // record that cannot be recomputed.
    let session = start(true).await;
    let id = session.doc_id.clone();
    post(
        &session,
        &format!("/api/docs/{id}/refactor/begin"),
        json!({}),
    )
    .await;

    std::fs::write(
        session.root.join("demo.hick"),
        BEFORE.replace("hello", "goodbye"),
    )
    .unwrap();

    let ended = post(&session, &format!("/api/docs/{id}/refactor/end"), json!({})).await;
    assert_eq!(ended["recorded"], json!(0), "{ended}");
    assert!(journal(&session).is_empty());
}

#[tokio::test]
async fn with_continuity_off_a_refactor_records_nothing_at_all() {
    // No continuity, no journal. An earlier design made the overlay opt-in
    // and the bookkeeping mandatory, which taxed every commit to feed a
    // feature most people never turn on.
    let session = start(false).await;
    let id = session.doc_id.clone();
    post(
        &session,
        &format!("/api/docs/{id}/refactor/begin"),
        json!({}),
    )
    .await;
    std::fs::write(session.root.join("demo.hick"), AFTER).unwrap();
    let ended = post(&session, &format!("/api/docs/{id}/refactor/end"), json!({})).await;
    assert_eq!(ended["recorded"], json!(0), "{ended}");
    assert!(!session.root.join(".hick-journal").exists());
}
