//! Samples: a window onto generated bytes, shown and never stored.
//!
//! Protects docs/guarantees/authoring/a-sample-shows-generated-lines-without-storing-them.md
//!
//! The thing worth testing is the whole reason the element exists: the lines
//! reach the reader, the document does not gain them, and every way the
//! window can stop pointing at anything says so out loud instead of showing
//! an empty box.

use std::process::Command;

fn hick() -> Command {
    Command::new(env!("CARGO_BIN_EXE_hick"))
}

/// A document whose cell writes three lines into a volume, and shows two of
/// them. Deliberately a VOLUME rather than a `hick:file`: a program wrote
/// these bytes, which is the case a sample is for.
fn doc(from: &str, to: &str) -> String {
    format!(
        r##"<?xml version="1.0" encoding="UTF-8"?>
<hick:doc xmlns:hick="http://www.hickorydocs.com/1.0" weave="api.md">
# Generated

<hick:volume name="gen" output="gen" />
<hick:exec container="sh" mount="gen:out">
mkdir -p out
printf 'alpha\nbeta\ngamma\n' > out/thing.txt
<hick:sample path="gen/thing.txt" from="{from}" to="{to}"
             caption="Two of the three" />
</hick:exec>
</hick:doc>
"##
    )
}

fn run(source: &str) -> (tempfile::TempDir, String) {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("api.hick");
    std::fs::write(&path, source).unwrap();
    let out = hick().arg("run").arg(&path).output().unwrap();
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let woven = std::fs::read_to_string(dir.path().join("api.md")).unwrap();
    (dir, woven)
}

#[test]
fn the_lines_reach_the_reader_and_the_document_never_gains_them() {
    let source = doc("2", "3");
    let (dir, woven) = run(&source);

    assert!(woven.contains("Two of the three"), "no caption:\n{woven}");
    assert!(woven.contains("beta\ngamma"), "no sampled lines:\n{woven}");
    // "alpha" is in the transcript (it is in the command); the sample block
    // itself must hold only the two lines asked for.
    let block = woven.split("```").nth(1).expect("a fenced sample");
    assert_eq!(
        block.trim(),
        "beta\ngamma",
        "wrong lines in the block:\n{woven}"
    );
    assert!(
        woven.contains("gen/thing.txt lines 2–3"),
        "the reader is not told where this came from:\n{woven}"
    );
    // The document is the point: it holds the element, not the bytes.
    let after = std::fs::read_to_string(dir.path().join("api.hick")).unwrap();
    assert_eq!(after, source, "the run wrote into the document");
    assert!(
        after.contains("hick:sample"),
        "the element is what the document holds"
    );
}

#[test]
fn a_sample_is_neither_the_command_nor_its_stdin() {
    // A cell fed its own output is the opposite of what a sample is for, and
    // a sample swept into the command text would be run as a shell line.
    let (_dir, woven) = run(&doc("1", "1"));
    assert!(
        !woven.contains("hick:sample"),
        "the element leaked into the transcript:\n{woven}"
    );
    assert!(
        !woven.contains("caption="),
        "the attributes reached the shell:\n{woven}"
    );
}

#[test]
fn a_range_past_the_end_of_the_file_says_so_rather_than_showing_nothing() {
    let (_dir, woven) = run(&doc("9", "12"));
    assert!(
        woven.contains("has 3 line(s)") && woven.contains("Re-pick"),
        "a slid-off range showed silently:\n{woven}"
    );
}

#[test]
fn a_file_that_was_never_generated_says_to_run_the_document() {
    let source = r##"<?xml version="1.0" encoding="UTF-8"?>
<hick:doc xmlns:hick="http://www.hickorydocs.com/1.0" weave="api.md">
<hick:exec container="sh">
echo hello
<hick:sample path="nowhere/thing.txt" from="1" to="2" />
</hick:exec>
</hick:doc>
"##;
    let (_dir, woven) = run(source);
    assert!(
        woven.contains("has not been generated yet"),
        "a missing file showed as an empty block:\n{woven}"
    );
}
