//! Turning a resolved [`Operation`] into source text.
//!
//! Everything hard happened in the resolver. An emitter walks a [`Shape`] and
//! writes types and one function per operation — which is why adding a
//! language is a file rather than a toolchain, and why the three here are
//! about a hundred lines each.
//!
//! Every emitter obeys the same two rules:
//!
//! * **The query text ships with its types.** They are generated together and
//!   cannot drift, which is the property a hand-written query string beside a
//!   hand-written struct does not have.
//! * **A variant selection stays a variant.** An interface selected with
//!   `... on ClassDecl` becomes a discriminated union in the target language,
//!   never a flattened object with optional fields — flattening is exactly
//!   what loses a record's positional parameters, and no schema here is
//!   allowed to lose that.

use super::{Field, Kind, Operation, Shape};

/// Which language to write.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Target {
    Python,
    TypeScript,
    Go,
}

impl Target {
    pub fn parse(name: &str) -> Option<Self> {
        match name {
            "python" | "py" => Some(Target::Python),
            "typescript" | "ts" => Some(Target::TypeScript),
            "go" | "golang" => Some(Target::Go),
            _ => None,
        }
    }

    pub fn names() -> &'static str {
        "python, typescript, go"
    }

    pub fn extension(self) -> &'static str {
        match self {
            Target::Python => "py",
            Target::TypeScript => "ts",
            Target::Go => "go",
        }
    }
}

/// Every named shape an operation produces, once each.
///
/// Deduplicated because the fields an interface selection has in common are
/// cloned into each of its variants, so a nested shape under those fields is
/// reached five times and keeps one path-derived name each time. Emitting it
/// five times is a duplicate declaration.
///
/// TypeScript hid this — it merges identical interfaces silently — and Go
/// refused to compile, which is the second time in this design that adding a
/// third language found what two agreed about.
fn shapes_of(op: &Operation) -> Vec<(String, Vec<Field>)> {
    let mut all = Vec::new();
    for field in &op.result.fields {
        collect(&field.shape, &mut all);
    }
    let mut seen = std::collections::HashSet::new();
    all.retain(|(name, _)| seen.insert(name.clone()));
    all
}

pub fn emit(target: Target, operations: &[Operation], language: &str) -> String {
    match target {
        Target::Python => python(operations, language),
        Target::TypeScript => typescript(operations, language),
        Target::Go => go(operations, language),
    }
}

fn banner(comment: &str, language: &str) -> String {
    format!(
        "{comment} Generated by `hick code-model {language} --client`. Do not edit.\n\
         {comment} The query text below is generated with its types, so the two cannot\n\
         {comment} drift. Change the query and regenerate.\n\n"
    )
}

/// Collect every named object shape, deepest first, so a type is declared
/// before it is used by languages that care.
fn collect(shape: &Shape, into: &mut Vec<(String, Vec<Field>)>) {
    match &shape.kind {
        Kind::List(inner) => collect(inner, into),
        Kind::Object(object) => {
            for field in &object.fields {
                collect(&field.shape, into);
            }
            into.push((object.name.clone(), object.fields.clone()));
        }
        // Each variant is a real named type. Without this the union referred
        // to names nothing declared, and the generated TypeScript did not
        // compile — caught by type-checking the output, which is the only
        // check a code generator's code generator can be trusted by.
        Kind::Variants(variants) => {
            for variant in variants {
                for field in &variant.fields {
                    collect(&field.shape, into);
                }
                into.push((variant.name.clone(), variant.fields.clone()));
            }
        }
        _ => {}
    }
}

// ---------------------------------------------------------------------------
// Python
// ---------------------------------------------------------------------------

fn python(operations: &[Operation], language: &str) -> String {
    let mut out = banner("#", language);
    out.push_str(
        "from __future__ import annotations\n\n\
         from dataclasses import dataclass\n\
         from typing import Any, Literal\n\n\
         from hick_model import Model\n\n\n",
    );
    for op in operations {
        for (name, fields) in &shapes_of(op) {
            out.push_str(&py_class(name, fields));
        }
        out.push_str(&py_class(&format!("{}Result", op.name), &op.result.fields));
        out.push_str(&format!(
            "{}_QUERY = \"\"\"\n{}\n\"\"\"\n\n\n",
            screaming(&op.name),
            op.text
        ));
        let params: Vec<String> = op
            .variables
            .iter()
            .map(|v| format!("{}: Any", v.name))
            .collect();
        let arglist = if params.is_empty() {
            String::new()
        } else {
            format!(", {}", params.join(", "))
        };
        let passthrough: Vec<String> = op
            .variables
            .iter()
            .map(|v| format!("{}={}", v.name, v.name))
            .collect();
        out.push_str(&format!(
            "def {}(model: Model{arglist}) -> {}Result:\n    \
             \"\"\"Ask `{}`, typed.\"\"\"\n    \
             return model.q({}_QUERY{})  # type: ignore[return-value]\n\n\n",
            snake(&op.name),
            op.name,
            op.name,
            screaming(&op.name),
            if passthrough.is_empty() {
                String::new()
            } else {
                format!(", {}", passthrough.join(", "))
            }
        ));
    }
    out
}

fn py_class(name: &str, fields: &[Field]) -> String {
    let mut out = format!("@dataclass(frozen=True)\nclass {}:\n", pascal(name));
    if fields.is_empty() {
        out.push_str("    pass\n\n\n");
        return out;
    }
    for field in fields {
        if let Some(doc) = &field.description {
            out.push_str(&format!("    # {}\n", doc.lines().next().unwrap_or("")));
        }
        out.push_str(&format!(
            "    {}: {}\n",
            py_name(&field.key),
            py_type(&field.shape)
        ));
    }
    out.push_str("\n\n");
    out
}

/// `__typename` is a dunder in Python and cannot be an attribute name, so it
/// is spelled `typename` — the one place a target language's rules override
/// the response's own spelling, and it is noted rather than silent.
fn py_name(key: &str) -> String {
    if key == "__typename" {
        "typename".to_string()
    } else {
        key.to_string()
    }
}

fn py_type(shape: &Shape) -> String {
    let inner = match &shape.kind {
        Kind::List(item) => format!("list[{}]", py_type(item)),
        Kind::Scalar(name) => match name.as_str() {
            "String" | "ID" => "str".into(),
            "Int" => "int".into(),
            "Float" => "float".into(),
            "Boolean" => "bool".into(),
            _ => "Any".into(),
        },
        Kind::Enum { values, .. } => format!(
            "Literal[{}]",
            values
                .iter()
                .map(|v| format!("\"{v}\""))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        Kind::Object(object) => pascal(&object.name),
        Kind::Variants(variants) => variants
            .iter()
            .map(|v| pascal(&v.name))
            .collect::<Vec<_>>()
            .join(" | "),
    };
    if shape.nullable {
        format!("{inner} | None")
    } else {
        inner
    }
}

// ---------------------------------------------------------------------------
// TypeScript
// ---------------------------------------------------------------------------

fn typescript(operations: &[Operation], language: &str) -> String {
    let mut out = banner("//", language);
    out.push_str("import type { Model } from \"./hick_model\";\n\n");
    for op in operations {
        for (name, fields) in &shapes_of(op) {
            out.push_str(&ts_interface(name, fields));
        }
        out.push_str(&ts_interface(
            &format!("{}Result", op.name),
            &op.result.fields,
        ));
        out.push_str(&format!(
            "export const {}_QUERY = `\n{}\n`;\n\n",
            screaming(&op.name),
            op.text
        ));
        let params: Vec<String> = op
            .variables
            .iter()
            .map(|v| format!("{}: unknown", v.name))
            .collect();
        out.push_str(&format!(
            "/** Ask `{}`, typed. */\nexport function {}(model: Model{}): Promise<{}Result> {{\n  \
             return model.q({}_QUERY{}) as Promise<{}Result>;\n}}\n\n",
            op.name,
            camel(&op.name),
            if params.is_empty() {
                String::new()
            } else {
                format!(", {}", params.join(", "))
            },
            op.name,
            screaming(&op.name),
            if op.variables.is_empty() {
                String::new()
            } else {
                format!(
                    ", {{ {} }}",
                    op.variables
                        .iter()
                        .map(|v| v.name.clone())
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            },
            op.name
        ));
    }
    out
}

fn ts_interface(name: &str, fields: &[Field]) -> String {
    let mut out = format!("export interface {} {{\n", pascal(name));
    for field in fields {
        if let Some(doc) = &field.description {
            out.push_str(&format!("  /** {} */\n", doc.lines().next().unwrap_or("")));
        }
        out.push_str(&format!(
            "  {}: {};\n",
            quote_key(&field.key),
            ts_type(&field.shape)
        ));
    }
    out.push_str("}\n\n");
    out
}

fn quote_key(key: &str) -> String {
    if key.starts_with("__") {
        format!("\"{key}\"")
    } else {
        key.to_string()
    }
}

fn ts_type(shape: &Shape) -> String {
    let inner = match &shape.kind {
        Kind::List(item) => format!("Array<{}>", ts_type(item)),
        Kind::Scalar(name) => match name.as_str() {
            "String" | "ID" => "string".into(),
            "Int" | "Float" => "number".into(),
            "Boolean" => "boolean".into(),
            _ => "unknown".into(),
        },
        Kind::Enum { values, .. } => values
            .iter()
            .map(|v| format!("\"{v}\""))
            .collect::<Vec<_>>()
            .join(" | "),
        Kind::Object(object) => pascal(&object.name),
        Kind::Variants(variants) => variants
            .iter()
            .map(|v| pascal(&v.name))
            .collect::<Vec<_>>()
            .join(" | "),
    };
    if shape.nullable {
        format!("{inner} | null")
    } else {
        inner
    }
}

// ---------------------------------------------------------------------------
// Go
// ---------------------------------------------------------------------------

fn go(operations: &[Operation], language: &str) -> String {
    let mut out = banner("//", language);
    out.push_str("package model\n\n");
    for op in operations {
        for (name, fields) in &shapes_of(op) {
            out.push_str(&go_struct(name, fields));
        }
        out.push_str(&go_struct(&format!("{}Result", op.name), &op.result.fields));
        out.push_str(&format!(
            "const {}Query = `\n{}\n`\n\n",
            pascal(&op.name),
            op.text
        ));
    }
    out
}

fn go_struct(name: &str, fields: &[Field]) -> String {
    let mut out = format!("type {} struct {{\n", pascal(name));
    for field in fields {
        if let Some(doc) = &field.description {
            out.push_str(&format!("\t// {}\n", doc.lines().next().unwrap_or("")));
        }
        // The json tag is not decoration here: Go's exported-by-capitalisation
        // means every field is renamed on the way in, and without the tag the
        // decoder silently leaves it zero.
        out.push_str(&format!(
            "\t{} {} `json:\"{}\"`\n",
            pascal(&field.key.replace("__", "")),
            go_type(&field.shape),
            field.key
        ));
    }
    out.push_str("}\n\n");
    out
}

fn go_type(shape: &Shape) -> String {
    let inner = match &shape.kind {
        Kind::List(item) => format!("[]{}", go_type(item)),
        Kind::Scalar(name) => match name.as_str() {
            "String" | "ID" => "string".into(),
            "Int" => "int".into(),
            "Float" => "float64".into(),
            "Boolean" => "bool".into(),
            _ => "any".into(),
        },
        // Go has no union type, so a variant selection is the widest struct
        // with the discriminator kept. Named rather than silently flattened:
        // the caller switches on Typename, which is what they would do in Go
        // anyway.
        Kind::Enum { .. } => "string".into(),
        Kind::Object(object) => pascal(&object.name),
        Kind::Variants(_) => "map[string]any".into(),
    };
    // A pointer only where a null is possible AND the zero value would lie.
    if shape.nullable && !inner.starts_with("[]") && !inner.starts_with("map[") {
        format!("*{inner}")
    } else {
        inner
    }
}

// ---------------------------------------------------------------------------
// Names
// ---------------------------------------------------------------------------

fn pascal(name: &str) -> String {
    name.split(['_', '-'])
        .filter(|p| !p.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn camel(name: &str) -> String {
    let p = pascal(name);
    let mut chars = p.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

fn snake(name: &str) -> String {
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.extend(ch.to_lowercase());
    }
    out
}

fn screaming(name: &str) -> String {
    snake(name).to_uppercase()
}
