// What goes inside a pane.
//
// The shell knows nothing about documents or generated files; these are the
// pieces that do, kept small so that adding a kind of view is adding a file
// rather than editing the shell.
//
// See docs/specs/freeform/shell-layouts.md.

import { useCallback, useEffect, useMemo, useState } from "react";
import type { Extension } from "@codemirror/state";

import { api } from "../api/client";
import type { OutputFile, OutputFileMeta } from "../api/types";
import { OutputEditorPane, provToChars, type ProvChar } from "../components/OutputEditorPane";
import { useOutputRealtime } from "../api/useOutputRealtime";

/** Where a character came from, in a few words rather than a panel. */
function describeOrigin(entry: ProvChar): string {
  const origin = entry.origin;
  if (origin.kind === "synthetic") return "generated by the weave";
  return `${origin.kind} from ${origin.doc_path}`;
}

/** One generated file, live, with its provenance carried into the LSP. */
export function GeneratedFileView({
  docId,
  path,
  makeOutputLsp,
  onSelectSpan,
}: {
  docId: string;
  path: string;
  makeOutputLsp?: (provenance: ProvChar[]) => Extension[];
  /** Jump to the document bytes this character came from. */
  onSelectSpan?: (span: [number, number]) => void;
}) {
  const [file, setFile] = useState<OutputFile | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [lineage, setLineage] = useState<ProvChar[]>([]);
  const realtime = useOutputRealtime(docId, path);

  useEffect(() => {
    let live = true;
    api.outputFile(docId, path).then(
      (loaded) => {
        if (live) {
          setFile(loaded);
          setError(null);
        }
      },
      (e) => live && setError(e instanceof Error ? e.message : String(e)),
    );
    return () => {
      live = false;
    };
  }, [docId, path]);

  const extensions = useMemo(
    () => (makeOutputLsp && file ? makeOutputLsp(provToChars(file)) : []),
    [makeOutputLsp, file],
  );

  if (error) return <p className="error">{error}</p>;
  if (!file || !realtime) return <p className="muted">Loading {path}…</p>;

  return (
    <div className="generated-view">
      <OutputEditorPane
        key={path}
        file={file}
        realtime={realtime}
        extensions={extensions}
        onLineage={setLineage}
      />
      {/* Where this text came from, on the text rather than in a panel: one
          line, and only when the cursor is somewhere with an answer. */}
      {/* Where this text came from, on the text rather than in a panel — and
          clickable, because the next question after "where from" is always
          "show me". */}
      {lineage.length > 0 && (
        <footer className="generated-view__lineage mono" role="status">
          <button
            type="button"
            disabled={!onSelectSpan || lineage[0].origin.kind === "synthetic"}
            onClick={() => {
              const origin = lineage[0].origin;
              if (origin.kind !== "synthetic") onSelectSpan?.(origin.span);
            }}
          >
            {describeOrigin(lineage[0])}
          </button>
          {lineage.length > 1 ? ` (+${lineage.length - 1} more)` : ""}
        </footer>
      )}
    </div>
  );
}

/**
 * The generated files this document produces.
 *
 * A tool, not a region: it describes the document rather than a part of the
 * codebase, and it exists because a freeform pane needs some way to find a
 * file before it can open it.
 */
export function OutputsTool({
  docId,
  onOpen,
  active,
}: {
  docId: string;
  onOpen: (path: string) => void;
  active?: string;
}) {
  const [files, setFiles] = useState<OutputFileMeta[] | null>(null);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(() => {
    api.outputs(docId).then(
      (r) => setFiles(r.files),
      (e) => setError(e instanceof Error ? e.message : String(e)),
    );
  }, [docId]);
  useEffect(load, [load]);

  if (error) return <p className="error">{error}</p>;
  if (files === null) return <p className="muted">Reading outputs…</p>;
  if (files.length === 0) {
    return (
      <p className="muted outputs-tool__empty">
        Nothing generated yet — run the document and its files appear here.
      </p>
    );
  }

  return (
    <ul className="outputs-tool">
      {files.map((file) => (
        <li key={file.path}>
          <button
            type="button"
            className={`outputs-tool__file mono${file.path === active ? " on" : ""}`}
            onClick={() => onOpen(file.path)}
          >
            {file.path}
          </button>
        </li>
      ))}
    </ul>
  );
}
