[package]
name = "hick-secrets"
version = "0.1.0"
edition = "2024"
publish = false
license.workspace = true

[dependencies]
age = "0.11"
async-trait = "0.1"
dashmap = "6"
secrecy = { version = "0.10", features = ["serde"] }
thiserror = "2"
tokio = { version = "1", features = ["rt"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
