// The refactor baseline, as document-toolbar chrome.
//
// "Refactor" pins the document's current woven outputs on the server
// (POST /refactor/begin); from then on this badge polls the live verdict —
// weave-only, no cell executes — and says either "Outputs match baseline"
// or which outputs moved. "Done" drops the baseline. The baseline is
// session state on the server, so the badge resumes after a tab close and
// re-open by asking for status on mount.

import { useCallback, useEffect, useRef, useState } from "react";

import { api } from "../api/client";
import type { RefactorStatus } from "../api/types";
import { refactorDetail, refactorSummary } from "../lib/refactorSummary";

/** How often the live verdict refreshes while a baseline is pinned. The
 * check weaves the document server-side (cached, never executing), so this
 * is cheap — and a badge that lags keystrokes by a couple of seconds is
 * still telling the truth about the last settled text. */
const POLL_MS = 2500;

export function RefactorBadge({ docId }: { docId: string }) {
  const [status, setStatus] = useState<RefactorStatus | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const liveRef = useRef(true);

  const refresh = useCallback(() => {
    api.refactorStatus(docId).then(
      (s) => {
        if (!liveRef.current) return;
        setStatus(s);
        setError(null);
      },
      (e) => liveRef.current && setError(e instanceof Error ? e.message : String(e)),
    );
  }, [docId]);

  // Resume on mount (the baseline outlives this tab), then poll while
  // active. The interval always runs off the LATEST status — an inactive
  // badge polls nothing.
  useEffect(() => {
    liveRef.current = true;
    refresh();
    return () => {
      liveRef.current = false;
    };
  }, [refresh]);
  const active = status?.active === true;
  useEffect(() => {
    if (!active) return;
    const timer = setInterval(refresh, POLL_MS);
    return () => clearInterval(timer);
  }, [active, refresh]);

  const begin = useCallback(() => {
    setBusy(true);
    api.refactorBegin(docId).then(
      (s) => {
        if (!liveRef.current) return;
        setBusy(false);
        setStatus(s);
        setError(null);
      },
      (e) => {
        if (!liveRef.current) return;
        setBusy(false);
        setError(e instanceof Error ? e.message : String(e));
      },
    );
  }, [docId]);

  const end = useCallback(() => {
    setBusy(true);
    api.refactorEnd(docId).then(
      (s) => {
        if (!liveRef.current) return;
        setBusy(false);
        setStatus(s);
      },
      () => liveRef.current && setBusy(false),
    );
  }, [docId]);

  if (!status || !status.active) {
    return (
      <>
        <button
          className="btn"
          disabled={busy || !status}
          onClick={begin}
          data-tip="Pin this document's woven outputs as a baseline, then restructure freely — the badge reports the moment any generated byte would change"
        >
          Refactor
        </button>
        {error && (
          <span className="error refactor-badge__error" role="status">
            {error}
          </span>
        )}
      </>
    );
  }

  const summary = refactorSummary(status);
  const detail = refactorDetail(status);
  return (
    <>
      <span
        className={`refactor-badge ${status.clean ? "refactor-badge--clean" : "refactor-badge--dirty"}`}
        role="status"
        {...(detail ? { "data-tip": detail } : {})}
      >
        {status.clean ? "✓ " : "△ "}
        {summary}
      </span>
      <button
        className="btn"
        disabled={busy}
        onClick={end}
        data-tip="Drop the baseline: the current outputs become the new truth"
      >
        Done
      </button>
      {error && (
        <span className="error refactor-badge__error" role="status">
          {error}
        </span>
      )}
    </>
  );
}
