[package]
name = "hick-literate"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "hick_literate"
path = "src/lib.rs"

[dependencies]
hickory-executor = { path = "../hickory-executor" }
hick-case = { path = "../hick-case" }
hick-condition = { path = "../hick-condition" }
hick-exec.workspace = true
hick-handlers = { path = "../hick-handlers" }
hick-feature = { path = "../hick-feature" }
hick-lang.workspace = true
hick-secrets = { path = "../hick-secrets" }
hick-token = { path = "../hick-token" }
hick-store = { path = "../hick-store" }
hick-merge = { path = "../hick-merge" }

tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-util", "sync", "time", "signal"] }
anyhow = "1"
chrono = { version = "0.4", default-features = false, features = ["std", "clock"] }
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
rand = "0.8"
regex = "1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_yaml = "0.9.34"
thiserror = "2"
glob = "0.3.3"
indexmap = "2"
walkdir = "2"
sha2 = "0.10.9"
base64 = "0.22"
tar = "0.4"
zip = "2"
notify = "7"
futures = "0.3"
sysinfo = "0.38.0"
pulldown-cmark = { version = "0.12", default-features = false, features = ["html"] }

[dev-dependencies]
tempfile = "3"
