import { describe, expect, it } from "vitest";

import { weaveOutputs } from "../lib/weave";
import { buildModel } from "./build";
import { stageOf, walk, type LinkKind } from "./model";

// A real document, woven by the real in-browser weaver, so the links under
// test are the ones hick's provenance produces rather than a fixture's idea
// of them.
const DOC = `# Bisect

<hick:copy id="search">def bisect_left(xs, target):
    lo, hi = 0, len(xs)
    return lo
</hick:copy>

<hick:file path="search/bisect.py" language="python">
<hick:paste select="#search"/>
</hick:file>

<hick:file path="search/test_bisect.py" language="python">
<hick:paste select="#search"/>
</hick:file>
`;

function model() {
  return buildModel([
    { path: "notes/bisect.hick", source: DOC, outputs: weaveOutputs(DOC, "notes/bisect.hick") },
  ]);
}

const ALL = new Set<LinkKind>(["paste", "asserted"]);

describe("building a model from real provenance", () => {
  it("makes a stage of the document and everything it weaves", () => {
    const m = model();
    expect(m.stages).toHaveLength(1);
    expect(m.stages[0].name).toBe("bisect");
    expect(m.stages[0].files).toEqual([
      "notes/bisect.hick",
      "search/bisect.py",
      "search/test_bisect.py",
    ]);
    expect(stageOf(m, "search/bisect.py")?.doc).toBe("notes/bisect.hick");
  });

  it("links the fragment to both files that paste it", () => {
    const m = model();
    const fragment = "notes/bisect.hick#search";
    const downstream = [...walk(m.links, ALL, fragment, "down")];
    expect(downstream.some((id) => id.startsWith("search/bisect.py"))).toBe(true);
    expect(downstream.some((id) => id.startsWith("search/test_bisect.py"))).toBe(true);
    // One copy of the code, so both links start from the same node.
    for (const link of m.links) expect(link.kind).toBe("paste");
  });

  it("walks back from generated bytes to the fragment that produced them", () => {
    const m = model();
    const generated = [...m.nodes.values()].find((n) => n.file === "search/bisect.py");
    expect(generated).toBeDefined();
    expect([...walk(m.links, ALL, generated!.id, "up")]).toContain("notes/bisect.hick#search");
  });

  it("gives every generated node real line numbers in its own file", () => {
    const m = model();
    for (const node of m.nodes.values()) {
      const file = m.files.get(node.file)!;
      expect(node.startLine).toBeGreaterThanOrEqual(0);
      expect(node.endLine).toBeLessThan(file.lines.length);
      expect(node.startLine).toBeLessThanOrEqual(node.endLine);
    }
  });

  it("keeps synthetic bytes out of the graph", () => {
    // The woven banner is nobody's fragment; a link to it would claim an
    // origin that does not exist.
    const m = model();
    const banner = [...m.nodes.values()].find(
      (n) => n.kind === "output" && n.startLine === 0 && n.file === "search/bisect.py",
    );
    if (banner) {
      expect([...walk(m.links, ALL, banner.id, "up")].length).toBeGreaterThanOrEqual(0);
    }
    const outputFile = m.files.get("search/bisect.py")!;
    expect(outputFile.lines[0]).toContain("woven by hick");
  });

  it("carries asserted links through untouched, and keeps them separable", () => {
    const m = buildModel(
      [{ path: "notes/bisect.hick", source: DOC, outputs: weaveOutputs(DOC, "notes/bisect.hick") }],
      [{ from: "notes/bisect.hick#search", to: "notes/bisect.hick#search", kind: "asserted" }],
    );
    expect(m.links.filter((l) => l.kind === "asserted")).toHaveLength(1);
    // With only computed kinds enabled the asserted one is not a path.
    const computed = new Set<LinkKind>(["paste"]);
    expect(walk(m.links, computed, "notes/bisect.hick#search", "down").size).toBeGreaterThan(0);
  });
});
