// The lineage browser's model: stages, the lines each column is showing, and
// the typed links between blocks.
//
// Everything here is pure. The two callers give it very different data — the
// desktop app reads documents and provenance from the local server, the
// marketing page weaves a document in the visitor's browser — and neither
// difference reaches the view, because both arrive as this shape.
//
// See docs/specs/freeform/stages-write-forward.md for what a stage is and the
// one rule about direction.

/** A file a column can open: a `.hick` document or something one generated. */
export interface FileModel {
  path: string;
  lines: string[];
  kind: "document" | "generated";
}

/** A block a link can attach to: a fragment, a file block, a cell, or a run of
 *  generated bytes that came from one of those. */
export interface LineageNode {
  id: string;
  file: string;
  /** Inclusive line range, 0-based. */
  startLine: number;
  endLine: number;
  label: string;
  /** `copy`, `file`, `exec`, … for documents; `output` for generated runs. */
  kind: string;
}

/**
 * How a link came to be. The distinction is the point: one is computed from
 * the weave and the other is a claim somebody made, and a picture that drew
 * them alike would be lying about which parts are checked.
 */
export type LinkKind = "paste" | "structural" | "asserted";

export const LINK_KINDS: Record<LinkKind, { label: string; detail: string }> = {
  paste: {
    label: "paste",
    detail:
      "Computed. These bytes are woven from that fragment, and an edit at either end " +
      "reaches the other.",
  },
  structural: {
    label: "structural",
    detail:
      "Name-matched by tree-sitter: this call and that definition share a name. It ships " +
      "in the download and needs no language server — and it is wrong wherever a name is " +
      "not unique, which it says by counting the candidates.",
  },
  asserted: {
    label: "asserted",
    detail:
      "Declared by a person: this influenced that. Nothing verifies it — the chain " +
      "records the claim, not its truth.",
  },
};

export interface Link {
  from: string;
  to: string;
  kind: LinkKind;
}

/** A document plus the files it generates. */
export interface Stage {
  /** Display name: the document, without folder or suffix. */
  name: string;
  /** The document that owns the stage. */
  doc: string;
  /** Every file in it, the document included. */
  files: string[];
}

export interface LineageModel {
  files: Map<string, FileModel>;
  nodes: Map<string, LineageNode>;
  links: Link[];
  stages: Stage[];
}

// ---------------------------------------------------------------------------
// Visible line ranges. The gaps between them are the holes, so growing a hole
// until it meets its neighbour and merging them are the same operation.
// ---------------------------------------------------------------------------

export type Range = [number, number];

export function normalizeRanges(ranges: Range[], max: number): Range[] {
  const clipped = ranges
    .map(([a, b]): Range => [Math.max(0, a), Math.min(max, b)])
    .filter(([a, b]) => a <= b)
    .sort((x, y) => x[0] - y[0]);
  const out: Range[] = [];
  for (const range of clipped) {
    const last = out[out.length - 1];
    // Touching counts as adjacent: with no line between them, a hole would
    // hide nothing, and a hole that hides nothing must not be drawn.
    if (last && range[0] <= last[1] + 1) last[1] = Math.max(last[1], range[1]);
    else out.push([...range]);
  }
  return out;
}

export function revealRange(ranges: Range[], from: number, to: number, max: number): Range[] {
  return normalizeRanges([...ranges, [from, to]], max);
}

/** Fold lines away. Subtracting a range can split one range in two, which is
 *  how a hole appears in the middle of a file. */
export function foldRange(ranges: Range[], from: number, to: number, max: number): Range[] {
  const out: Range[] = [];
  for (const [a, b] of ranges) {
    if (to < a || from > b) {
      out.push([a, b]);
      continue;
    }
    if (from > a) out.push([a, from - 1]);
    if (to < b) out.push([to + 1, b]);
  }
  return normalizeRanges(out, max);
}

/** The holes implied by a set of visible ranges. */
export function holesOf(ranges: Range[], max: number): Range[] {
  const out: Range[] = [];
  let cursor = 0;
  for (const [a, b] of ranges) {
    if (a > cursor) out.push([cursor, a - 1]);
    cursor = b + 1;
  }
  if (cursor <= max) out.push([cursor, max]);
  return out;
}

export function fullRange(file: FileModel): Range[] {
  return [[0, Math.max(0, file.lines.length - 1)]];
}

/** Lines matching `query`, case-insensitively. */
export function matchingLines(file: FileModel, query: string): Set<number> {
  const needle = query.trim().toLowerCase();
  const out = new Set<number>();
  if (!needle) return out;
  file.lines.forEach((line, i) => {
    if (line.toLowerCase().includes(needle)) out.add(i);
  });
  return out;
}

/**
 * Fold a file down to the given lines, keeping `context` lines around each.
 *
 * The hits come from the ranked index rather than from a substring scan, so
 * "which lines" and "in what order they matter" are decided in one place
 * (see bm25.ts) instead of drifting between the fold and the ranking.
 */
export function rangesForLines(
  file: FileModel,
  lines: Iterable<number>,
  context = 2,
): Range[] {
  const max = Math.max(0, file.lines.length - 1);
  const ranges = [...lines].map((i): Range => [i - context, i + context]);
  if (!ranges.length) return [];
  return normalizeRanges(ranges, max);
}

/** Fold a file to the lines literally containing `query`. Kept for callers
 *  with no index to hand; the browser uses the ranked path. */
export function searchRanges(file: FileModel, query: string, context = 2): Range[] {
  if (!query.trim()) return fullRange(file);
  return rangesForLines(file, matchingLines(file, query), context);
}

// ---------------------------------------------------------------------------
// Traversal
// ---------------------------------------------------------------------------

/**
 * Everything reachable from `id`, following only the kinds in `kinds`.
 *
 * Filtering by kind changes the GRAPH, not just the drawing: turning off the
 * kinds nothing verifies has to make the chain as short as the verified links
 * really make it, or the filter would be decoration.
 */
export function walk(
  links: Link[],
  kinds: Set<LinkKind>,
  id: string,
  direction: "up" | "down",
): Set<string> {
  const seen = new Set<string>();
  const queue = [id];
  while (queue.length) {
    const current = queue.shift()!;
    for (const link of links) {
      if (!kinds.has(link.kind)) continue;
      const next =
        direction === "up"
          ? link.to === current
            ? link.from
            : null
          : link.from === current
            ? link.to
            : null;
      if (next && !seen.has(next)) {
        seen.add(next);
        queue.push(next);
      }
    }
  }
  return seen;
}

/** The stage that owns a file, or undefined for a file outside the pipeline. */
export function stageOf(model: LineageModel, path: string): Stage | undefined {
  return model.stages.find((s) => s.files.includes(path));
}

/** The node covering a line, if any. */
export function nodeAt(model: LineageModel, path: string, line: number): LineageNode | undefined {
  let best: LineageNode | undefined;
  for (const node of model.nodes.values()) {
    if (node.file !== path || line < node.startLine || line > node.endLine) continue;
    // The tightest enclosing node wins: a paste inside a file block should
    // select the paste, not the file that contains it.
    if (!best || node.endLine - node.startLine < best.endLine - best.startLine) best = node;
  }
  return best;
}
