//! Core types for the version store.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// Content-addressed blob hash (SHA-256 hex).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct BlobHash(pub String);

impl BlobHash {
    /// Compute the SHA-256 hash of content.
    pub fn of(content: &[u8]) -> Self {
        use sha2::Digest;
        let hash = sha2::Sha256::digest(content);
        BlobHash(hex::encode(hash))
    }
}

impl std::fmt::Display for BlobHash {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Snapshot identifier (SHA-256 hex of snapshot content, or git commit SHA).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SnapshotId(pub String);

impl std::fmt::Display for SnapshotId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// How a file in a snapshot was produced.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum FileProvenance {
    /// Generated from a .hick source file.
    HickFile { source: String },
    /// Output from a container execution writing to a volume.
    ContainerOutput { container: String, volume: String },
    /// A .hick file generated by a container (used as input to a subsequent stage).
    GeneratedHick { source_container: String },
    /// Created directly by the user (not generated).
    UserCreated,
}

/// An immutable snapshot of pipeline state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Snapshot {
    /// Unique identifier for this snapshot.
    pub id: SnapshotId,
    /// Parent snapshot(s). Empty for the initial snapshot.
    pub parents: Vec<SnapshotId>,
    /// File path → blob hash for each file in this snapshot.
    pub files: BTreeMap<String, BlobHash>,
    /// File path → provenance for each file.
    pub provenance: BTreeMap<String, FileProvenance>,
    /// Unix timestamp (seconds since epoch).
    pub timestamp: u64,
    /// Optional human-readable message.
    pub message: Option<String>,
}

impl Snapshot {
    /// Compute the canonical ID for this snapshot based on its content.
    ///
    /// The ID is the SHA-256 of the JSON serialization of the snapshot
    /// (with the `id` field set to empty).
    pub fn compute_id(&self) -> SnapshotId {
        use sha2::Digest;
        let mut canonical = self.clone();
        canonical.id = SnapshotId(String::new());
        let json = serde_json::to_string(&canonical).unwrap_or_default();
        let hash = sha2::Sha256::digest(json.as_bytes());
        SnapshotId(hex::encode(hash))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn blob_hash_deterministic() {
        let h1 = BlobHash::of(b"hello world");
        let h2 = BlobHash::of(b"hello world");
        assert_eq!(h1, h2);

        let h3 = BlobHash::of(b"different");
        assert_ne!(h1, h3);
    }

    #[test]
    fn snapshot_id_deterministic() {
        let s1 = Snapshot {
            id: SnapshotId(String::new()),
            parents: vec![],
            files: BTreeMap::from([("a.txt".to_string(), BlobHash::of(b"aaa"))]),
            provenance: BTreeMap::new(),
            timestamp: 1000,
            message: None,
        };
        let id1 = s1.compute_id();
        let id2 = s1.compute_id();
        assert_eq!(id1, id2);
    }

    #[test]
    fn snapshot_serialization_roundtrip() {
        let snapshot = Snapshot {
            id: SnapshotId("abc123".to_string()),
            parents: vec![SnapshotId("parent1".to_string())],
            files: BTreeMap::from([("file.txt".to_string(), BlobHash::of(b"content"))]),
            provenance: BTreeMap::from([(
                "file.txt".to_string(),
                FileProvenance::HickFile {
                    source: "main.hick".to_string(),
                },
            )]),
            timestamp: 12345,
            message: Some("test snapshot".to_string()),
        };

        let json = serde_json::to_string(&snapshot).unwrap();
        let parsed: Snapshot = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.id, snapshot.id);
        assert_eq!(parsed.files.len(), 1);
        assert_eq!(parsed.message, Some("test snapshot".to_string()));
    }
}
