//! The native Insert menu and the page's catalogue name the same elements.
//!
//! Protects docs/guarantees/authoring/inserting-an-element-writes-hick-you-could-have-typed.md
//!
//! The catalogue (`apps/web/src/lib/insertCatalog.ts`) owns what an element
//! IS — its attributes, its hints, the bytes it writes. The native menu owns
//! only the names, so the two lists can drift, and a drift is a real defect
//! in both directions: a menu item for an element the page dropped opens the
//! panel on the wrong thing, and an element the menu never got is one a
//! desktop user can only reach through the keyboard.
//!
//! Read as text rather than parsed. A regex over `id: "…"` is enough because
//! the file is generated by nobody and edited by hand, and a check that costs
//! a TypeScript toolchain to run would not run.

use std::collections::BTreeSet;
use std::path::PathBuf;

fn catalogue_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../web/src/lib/insertCatalog.ts")
        .canonicalize()
        .expect("the web catalogue is a sibling of the desktop shell")
}

/// Every `id:` of an element entry, in catalogue order.
fn catalogue_ids(source: &str) -> Vec<String> {
    let mut ids = Vec::new();
    for line in source.lines() {
        let line = line.trim();
        // Element entries are `id: "name",` at the top of each object; a
        // field's `name:` and the tag's `tag:` are spelled differently.
        if let Some(rest) = line.strip_prefix("id: \"")
            && let Some(id) = rest.split('"').next()
        {
            ids.push(id.to_string());
        }
    }
    ids
}

#[test]
fn every_menu_item_names_a_real_element() {
    let source = std::fs::read_to_string(catalogue_path()).expect("read the catalogue");
    let known: BTreeSet<String> = catalogue_ids(&source).into_iter().collect();
    assert!(
        known.len() > 20,
        "the catalogue parse found only {} elements — the file's shape changed",
        known.len()
    );

    let mut missing = Vec::new();
    for (_, elements) in hickory_desktop_lib::insert_menu_elements() {
        for (id, _) in elements.iter() {
            if !known.contains(*id) {
                missing.push(*id);
            }
        }
    }
    assert!(
        missing.is_empty(),
        "the Insert menu names elements the page does not have: {missing:?}"
    );
}

#[test]
fn every_element_is_reachable_from_the_menu() {
    let source = std::fs::read_to_string(catalogue_path()).expect("read the catalogue");
    let listed: BTreeSet<&str> = hickory_desktop_lib::insert_menu_elements()
        .iter()
        .flat_map(|(_, elements)| elements.iter().map(|(id, _)| *id))
        .collect();

    let unreachable: Vec<String> = catalogue_ids(&source)
        .into_iter()
        .filter(|id| !listed.contains(id.as_str()))
        .collect();
    assert!(
        unreachable.is_empty(),
        "elements the page offers but the native menu does not: {unreachable:?}"
    );
}
