//! Adoption and the refactor baseline — the equivalence surface of the app.
//!
//! Two flows share one invariant, "no generated byte moves unless you meant
//! it to":
//!
//! - `POST /api/adopt` wraps a plain file into a document byte-exactly
//!   (crate::adopt), the on-ramp from a non-literate repository.
//! - `POST /docs/:id/refactor/begin` pins the document's current woven
//!   outputs as a baseline; `GET …/refactor/status` weaves the live text
//!   and compares against that baseline with the same checker `hick equiv`
//!   uses (`hick_literate::equiv::compare_outputs`); `POST …/refactor/end`
//!   drops it. Restructure freely between begin and end — the badge in the
//!   document toolbar tells the truth the whole time.
//!
//! Status checks are weave-only — no cell executes — which is what makes a
//! live badge affordable: the same reason `/render` never executes.
//!
//! The baseline lives in this process's memory, keyed by document id. That
//! is deliberate: a refactor session is a session, not a property of the
//! repository — closing the app ends it, and git still holds the durable
//! before-state.

use std::collections::HashMap;

use axum::Json;
use axum::extract::{Path, State};
use hick_exec::node::FileContent;
use hick_literate::equiv::{DiffKind, compare_outputs};
use serde::Deserialize;
use serde_json::{Value, json};

use super::LocalState;
use super::api::{ApiError, ApiResult};

/// One pinned baseline: each output path to its content's string form —
/// exactly what `compare_outputs` compares by — plus the LINEAGE of those
/// outputs at the moment they were pinned.
///
/// The provenance is what turns refactor mode from an equivalence check into
/// the recording site the continuity design needs. Refactor mode is a machine
/// for destroying textual continuity while guaranteeing semantic identity:
/// pin a baseline, restructure, and the outputs are proven unchanged while
/// blame afterwards says every line is new. Because the outputs are proven
/// identical they are a **join key** — an output byte maps to a span in the
/// baseline document and to a span in the restructured one, and composing the
/// two gives the correspondence exactly, with no identity scheme involved.
///
/// It is captured at `begin`, when the working tree IS the baseline. Storing
/// only the text and re-weaving it later would need the siblings it reads
/// (pastes, upstream edges) as they were then, which the working tree no
/// longer has.
pub struct RefactorBaseline {
    pub outputs: HashMap<String, String>,
    /// Output path → the lineage of those bytes in the baseline document.
    pub provenance: HashMap<String, Vec<hickory_lineage::Provenance>>,
    pub started_at: String,
}

/// The stored strings, rebuilt as the map the shared checker takes.
fn as_file_contents(outputs: &HashMap<String, String>) -> HashMap<String, FileContent> {
    outputs
        .iter()
        .map(|(path, text)| (path.clone(), FileContent::Text(text.clone())))
        .collect()
}

// ---------------------------------------------------------------------------
// Adoption
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
pub struct AdoptRequest {
    /// Root-relative path of the plain file to adopt.
    pub path: String,
    /// Root-relative path of an existing document to append to, instead of
    /// creating `<stem>.hick` beside the file.
    #[serde(default)]
    pub into: Option<String>,
}

/// `POST /api/adopt` — adopt a plain file into a document, byte-exactly.
pub async fn adopt(
    State(state): State<LocalState>,
    Json(body): Json<AdoptRequest>,
) -> ApiResult<Json<Value>> {
    let root = state.index.root().to_path_buf();
    let file = resolve_in_root(&root, &body.path)?;
    let outcome = match &body.into {
        Some(doc_rel) => {
            let doc = resolve_in_root(&root, doc_rel)?;
            if !doc_rel.ends_with(".hick") {
                return Err(ApiError::bad_request(format!(
                    "{doc_rel} is not a document — --into takes a `.hick` file"
                )));
            }
            crate::adopt::adopt_into(&file, &doc).await
        }
        None => crate::adopt::adopt_new(&file).await,
    }
    .map_err(|e| ApiError::unprocessable(format!("{e:#}")))?;

    // Register the (possibly new) document so it opens without a restart.
    let doc_rel = outcome
        .doc_path
        .strip_prefix(&root)
        .map(|p| p.to_string_lossy().replace('\\', "/"))
        .map_err(|_| ApiError::internal("the adopted document landed outside the folder"))?;
    let doc_id = state.index.add(&doc_rel);
    Ok(Json(json!({
        "doc_id": doc_id,
        "doc_path": doc_rel,
        "file_path": body.path,
        // How the weave names this output: relative to the document's
        // directory. The client's generated pane fetches by this key.
        "output_path": outcome.output_path,
        "created": outcome.created,
    })))
}

/// A root-relative request path, joined and bounds-checked. Same rules as
/// the plain-file surface: relative, no `..`, inside the folder.
fn resolve_in_root(root: &std::path::Path, rel: &str) -> Result<std::path::PathBuf, ApiError> {
    let rel = rel.trim();
    let as_path = std::path::Path::new(rel);
    let escapes = rel.is_empty()
        || as_path.is_absolute()
        || as_path
            .components()
            .any(|c| !matches!(c, std::path::Component::Normal(_)));
    if escapes {
        return Err(ApiError::bad_request(format!(
            "path must be relative to the open folder, with no `..` — got {rel:?}"
        )));
    }
    Ok(root.join(rel))
}

// ---------------------------------------------------------------------------
// The refactor baseline
// ---------------------------------------------------------------------------

/// `POST /api/docs/:id/refactor/begin` — pin the current outputs.
pub async fn begin(
    State(state): State<LocalState>,
    Path(id): Path<String>,
) -> ApiResult<Json<Value>> {
    let run = state.weave(&id).await?;
    let outputs: HashMap<String, String> = run
        .result
        .files
        .iter()
        .map(|(path, content)| (path.clone(), content.to_string()))
        .collect();
    // The lineage of every output, as it stands. A document that will not
    // report lineage for one output still pins the rest: the equivalence
    // check is the primary job here and must not be lost to the recording.
    let provenance: HashMap<String, Vec<hickory_lineage::Provenance>> = outputs
        .keys()
        .filter_map(|path| {
            crate::output_lineage(&run, path)
                .ok()
                .map(|p| (path.clone(), p))
        })
        .collect();
    let started_at = super::now_rfc3339();
    let listing: Vec<&String> = outputs.keys().collect();
    let body = json!({
        "active": true,
        "started_at": started_at,
        "files": listing,
        "clean": true,
        "diffs": [],
    });
    state.refactors.lock().unwrap().insert(
        id,
        RefactorBaseline {
            outputs,
            provenance,
            started_at,
        },
    );
    Ok(Json(body))
}

/// `GET /api/docs/:id/refactor/status` — the live equivalence verdict.
///
/// `{active: false}` when no baseline is pinned; otherwise `clean` plus one
/// entry per output that differs — `changed`, `added` (not in the
/// baseline), or `removed` (the baseline had it, the live text does not).
pub async fn status(
    State(state): State<LocalState>,
    Path(id): Path<String>,
) -> ApiResult<Json<Value>> {
    let (baseline, started_at) = {
        let map = state.refactors.lock().unwrap();
        match map.get(&id) {
            None => return Ok(Json(json!({ "active": false }))),
            Some(b) => (as_file_contents(&b.outputs), b.started_at.clone()),
        }
    };
    let run = state.weave(&id).await?;
    let diffs = compare_outputs(&baseline, &run.result.files);
    let entries: Vec<Value> = diffs
        .iter()
        .map(|d| {
            json!({
                "path": d.path,
                "kind": match d.kind {
                    DiffKind::OnlyInFirst => "removed",
                    DiffKind::OnlyInSecond => "added",
                    DiffKind::ContentDiffers { .. } => "changed",
                },
            })
        })
        .collect();
    Ok(Json(json!({
        "active": true,
        "started_at": started_at,
        "clean": entries.is_empty(),
        "diffs": entries,
    })))
}

/// `POST /api/docs/:id/refactor/end` — drop the baseline, recording what the
/// restructure moved if continuity is on.
///
/// This is the highest-value recording site per line of code in the whole
/// design, and the reason is that the work is already done: the outputs were
/// proven identical, so they are a join key, and the correspondence falls out
/// of composing two lineages that both already exist.
///
/// **Only when the outputs still match.** A restructure that changed what the
/// document produces has not preserved anything, so there is nothing to say
/// two spans are the same thing — and recording it anyway would put a false
/// fact in a record that cannot be recomputed.
///
/// **And only when continuity is on.** No continuity, no journal: the switch
/// is the whole feature, not just its drawing.
pub async fn end(State(state): State<LocalState>, Path(id): Path<String>) -> Json<Value> {
    let baseline = state.refactors.lock().unwrap().remove(&id);
    let Some(baseline) = baseline else {
        return Json(json!({ "active": false }));
    };

    let root = state.index.root().to_path_buf();
    if !crate::continuity::enabled(&root) {
        return Json(json!({ "active": false, "recorded": 0 }));
    }

    let recorded = record_refactor(&state, &id, &baseline, &root)
        .await
        .unwrap_or(0);
    Json(json!({ "active": false, "recorded": recorded }))
}

/// Compose the baseline's lineage with the restructured document's, over the
/// outputs proven identical, and append what moved to the journal.
async fn record_refactor(
    state: &LocalState,
    id: &str,
    baseline: &RefactorBaseline,
    root: &std::path::Path,
) -> Option<usize> {
    let run = state.weave(id).await.ok()?;
    // Equivalence first. `compare_outputs` is the same checker `hick equiv`
    // and the badge use, so "proven identical" means one thing everywhere.
    if !compare_outputs(&as_file_contents(&baseline.outputs), &run.result.files).is_empty() {
        return Some(0);
    }

    let head = super::git_head(root);
    let today = crate::ingest::today().unwrap_or_else(|| "unknown".to_string());
    let mut entries = Vec::new();
    for (path, before) in &baseline.provenance {
        let Ok(after) = crate::output_lineage(&run, path) else {
            continue;
        };
        for (from, to) in crate::continuity::join_through_outputs(before, after.as_slice()) {
            entries.push(crate::continuity::Correspondence {
                from,
                to,
                // Byte-exact: joined through outputs proven identical, which
                // is the strongest precision any site here produces.
                precision: crate::continuity::Precision::Byte,
                site: crate::continuity::Site::Refactor,
                // Both ends are the working tree, which is above the floor by
                // definition — so the address this is keyed on can still be
                // replaced by a re-emission.
                provisional: true,
                head: head.clone(),
                recorded_at: today.clone(),
            });
        }
    }
    crate::continuity::Journal::at(root).append(&entries).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stored_strings_round_trip_through_the_shared_checker() {
        let mut base = HashMap::new();
        base.insert("a.py".to_string(), "print(1)\n".to_string());
        base.insert("b.txt".to_string(), "kept\n".to_string());

        let mut current = HashMap::new();
        current.insert("a.py".to_string(), FileContent::Text("print(2)\n".into()));
        current.insert("c.txt".to_string(), FileContent::Text("new\n".into()));

        let diffs = compare_outputs(&as_file_contents(&base), &current);
        let mut kinds: Vec<(String, &str)> = diffs
            .iter()
            .map(|d| {
                (
                    d.path.clone(),
                    match d.kind {
                        DiffKind::OnlyInFirst => "removed",
                        DiffKind::OnlyInSecond => "added",
                        DiffKind::ContentDiffers { .. } => "changed",
                    },
                )
            })
            .collect();
        kinds.sort();
        assert_eq!(
            kinds,
            vec![
                ("a.py".to_string(), "changed"),
                ("b.txt".to_string(), "removed"),
                ("c.txt".to_string(), "added"),
            ]
        );
    }
}
