//! Picking a sample: `POST /api/samples`.
//!
//! A generator exists so nobody reads its output, and a document that pasted
//! the output back in would undo the thing it exists for. But a reader still
//! has to see WHAT the generator makes, once, before they will believe the
//! rules — so a sample is a window: a few lines of a generated file, shown
//! under the cell that generated it.
//!
//! **The bytes are never written into the document.** What lands in the
//! `.hick` is one self-closing element naming a path and a line range; the
//! lines themselves appear only in the weave. That is what makes a sample
//! free to keep — it costs the document one line, it cannot go stale without
//! the drift check saying so, and it cannot be edited into a lie, because
//! there is nothing there to edit.
//!
//! This endpoint is the pick gesture. You select lines in the generated pane
//! and the app writes the element into the right cell, which is the part a
//! person should not have to do by hand: finding which of seven documents
//! and which of its cells wrote a file two directories away is exactly the
//! bookkeeping the file tree already does.

use axum::Json;
use axum::extract::State;
use serde::Deserialize;
use serde_json::{Value, json};

use super::LocalState;
use super::api::{ApiError, ApiResult, generated_by};

#[derive(Deserialize)]
pub struct SampleRequest {
    /// Root-relative path of the generated file to sample.
    pub path: String,
    /// First line to show, 1-based and inclusive.
    pub from: usize,
    /// Last line to show, 1-based and inclusive.
    pub to: usize,
    /// The one line of prose above the sample saying what it illustrates.
    #[serde(default)]
    pub caption: Option<String>,
}

/// `POST /api/samples` — put a `<hick:sample>` under the cell that generated
/// this file.
pub async fn create(
    State(state): State<LocalState>,
    Json(body): Json<SampleRequest>,
) -> ApiResult<Json<Value>> {
    if body.from == 0 || body.to < body.from {
        return Err(ApiError::bad_request(format!(
            "a sample runs from one line to a later one — got {}–{}",
            body.from, body.to
        )));
    }
    let root = state.index.root().to_path_buf();
    let generated = super::api::generated_outputs(&root, &state.index);
    let doc_id = generated_by(&generated, &body.path).ok_or_else(|| {
        ApiError::unprocessable(format!(
            "no document in this folder generates {} — a sample can only show \
             generated bytes, since hand-written ones belong in the document itself",
            body.path
        ))
    })?;
    let doc_rel = state.index.path_of(&doc_id).ok_or_else(|| {
        ApiError::internal(format!("the document generating {} has no path", body.path))
    })?;
    let source = state.read_source_by_doc_path(&doc_rel)?;

    // Where the document says it writes this — the volume output or the
    // `hick:file` — is what tells us which cell to put the sample under.
    let anchor = declaring_offset(&doc_rel, &source, &body.path).ok_or_else(|| {
        ApiError::unprocessable(format!(
            "{doc_rel} generates {} but does not name it in a way this can find \
             (a path built from a variable, most likely) — add the \
             `<hick:sample>` by hand",
            body.path
        ))
    })?;
    let (insert_at, indent) = insertion_point(&source, anchor).ok_or_else(|| {
        ApiError::unprocessable(format!(
            "{doc_rel} writes {} outside any cell, so there is no run for a \
             sample to sit under",
            body.path
        ))
    })?;

    // `path=` is relative to the document, the same as everywhere else in the
    // language — the reader of the `.hick` should see the path they would
    // type, not one rebased on the folder root.
    let rel_to_doc = relative_to_doc(&doc_rel, &body.path);
    let mut element = format!(
        "{indent}<hick:sample path=\"{rel_to_doc}\" from=\"{}\" to=\"{}\"",
        body.from, body.to
    );
    if let Some(caption) = body
        .caption
        .as_deref()
        .map(str::trim)
        .filter(|c| !c.is_empty())
    {
        if caption.contains('"') {
            return Err(ApiError::bad_request(
                "a caption cannot contain a double quote — it is an attribute value".to_string(),
            ));
        }
        element.push_str(&format!("\n{indent}             caption=\"{caption}\""));
    }
    element.push_str(" />\n");

    let mut updated = source.clone();
    updated.insert_str(insert_at, &element);
    hick_lang::parse(&updated).map_err(|e| {
        ApiError::unprocessable(format!("the sample would make {doc_rel} unparseable: {e}"))
    })?;

    state.write_source_by_doc_path(&doc_rel, &updated)?;
    state.rooms.apply_external_source(&doc_id, &updated).await;

    Ok(Json(json!({
        "doc_id": doc_id,
        "doc_path": doc_rel,
        "path": rel_to_doc,
        "from": body.from,
        "to": body.to,
    })))
}

/// The byte offset of the attribute by which `doc_rel` claims `path`.
///
/// Uses the same reading of the source the file tree uses, so a file the tree
/// marks generated is a file this can find — and one it cannot is one the
/// tree could not have marked either.
fn declaring_offset(doc_rel: &str, source: &str, path: &str) -> Option<usize> {
    let dir = doc_rel.rsplit_once('/').map(|(d, _)| d).unwrap_or("");
    let mut best: Option<(usize, usize)> = None; // (specificity, offset)
    for (offset, value) in declared_attribute_values(source) {
        let claimed = super::api::join_under(dir, &value)?;
        // Either this file exactly, or a directory it lies under.
        let claims = claimed == path
            || (path.starts_with(&claimed) && path.as_bytes().get(claimed.len()) == Some(&b'/'));
        let hit = claims.then_some(claimed.len());
        // Longest claim wins, matching `generated_by`: a narrow volume nested
        // inside a wider one is the cell that actually wrote the file.
        if let Some(len) = hit
            && best.is_none_or(|(best_len, _)| len > best_len)
        {
            best = Some((len, offset));
        }
    }
    best.map(|(_, offset)| offset)
}

/// Every `path=`/`output=` value in the source, with where it starts.
fn declared_attribute_values(source: &str) -> Vec<(usize, String)> {
    let mut out = Vec::new();
    for pattern in [
        r#"<hick:file\b[^>]*?\bpath\s*=\s*"([^"]*)""#,
        r#"<hick:volume\b[^>]*?\boutput\s*=\s*"([^"]*)""#,
    ] {
        let re = regex::Regex::new(pattern).expect("the declaring-attribute pattern compiles");
        for capture in re.captures_iter(source) {
            let whole = capture.get(0).expect("a match has a whole");
            out.push((whole.start(), capture[1].to_string()));
        }
    }
    out
}

/// Where inside the enclosing cell the sample goes, and how far it is
/// indented: the last line before `</hick:exec>`.
///
/// Last, because a sample is an illustration of what the run produced and
/// belongs after the expectation that checks it, the same way the reader
/// meets them: the rule, then one example of the rule.
fn insertion_point(source: &str, anchor: usize) -> Option<(usize, String)> {
    let open = source[..anchor].rfind("<hick:exec")?;
    let close = source[anchor..].find("</hick:exec>")? + anchor;
    // A `hick:file` outside any cell can still sit before a later cell's
    // opening tag; only an anchor genuinely inside this one counts.
    if source[open..close].contains("</hick:exec>") {
        return None;
    }
    let line_start = source[..close].rfind('\n').map(|i| i + 1).unwrap_or(0);
    let indent: String = source[line_start..close]
        .chars()
        .take_while(|c| *c == ' ' || *c == '\t')
        .collect();
    Some((line_start, indent))
}

/// A root-relative path, rewritten relative to the document that will name
/// it. Only the easy direction is handled — a document at the root, or an
/// output beneath the document's own directory — because those are the ones
/// the language can express without `..`.
fn relative_to_doc(doc_rel: &str, path: &str) -> String {
    let Some(dir) = doc_rel.rsplit_once('/').map(|(d, _)| d) else {
        return path.to_string();
    };
    path.strip_prefix(&format!("{dir}/"))
        .unwrap_or(path)
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    const DOC: &str = r#"# The API

<hick:exec container="gen">
python3 gen.py
<hick:volume name="out" output="src/Api/Generated" mode="output" />
<hick:expect>
8 endpoints
</hick:expect>
</hick:exec>
"#;

    #[test]
    fn a_volume_output_is_traced_back_to_the_cell_that_wrote_it() {
        let anchor = declaring_offset("30-api.hick", DOC, "src/Api/Generated/Endpoints.g.cs")
            .expect("the volume claims it");
        let (at, indent) = insertion_point(DOC, anchor).expect("the volume is inside a cell");
        assert_eq!(indent, "");
        // Immediately before the closing tag, after the expectation.
        assert!(DOC[at..].starts_with("</hick:exec>"));
    }

    #[test]
    fn a_file_written_outside_a_cell_has_nowhere_to_hang_a_sample() {
        let doc = "<hick:file path=\"a.rs\">\nfn main() {}\n</hick:file>\n";
        let anchor = declaring_offset("d.hick", doc, "a.rs").expect("the file claims it");
        assert!(insertion_point(doc, anchor).is_none());
    }

    #[test]
    fn the_path_is_written_the_way_the_document_would_name_it() {
        assert_eq!(
            relative_to_doc("docs/30-api.hick", "docs/src/x.cs"),
            "src/x.cs"
        );
        assert_eq!(relative_to_doc("30-api.hick", "src/x.cs"), "src/x.cs");
    }
}
