

"""Quarterly sales report.

Assembled by `hick run` from examples/grand-tour.hick.
Do not edit this file directly - edit the document (or edit this file in the
Hickory web editor, where lineage maps every character back to its source
section).
"""

def lcg(seed):
    """Deterministic 31-bit linear congruential generator."""
    state = seed
    while True:
        state = (state * 1103515245 + 12345) % (2 ** 31)
        yield state

REGIONS = ["east", "north", "south", "west"]


def make_sales(seed=2026, n=24):
    """Return `n` synthetic sales rows: (region, units, unit_price)."""
    rng = lcg(seed)
    rows = []
    for i in range(n):
        region = REGIONS[i % len(REGIONS)]
        units = 1 + next(rng) % 50
        unit_price = 10.0 + (next(rng) % 9000) / 100.0
        rows.append((region, units, round(unit_price, 2)))
    return rows

def revenue_by_region(rows):
    totals = {}
    for region, units, unit_price in rows:
        totals[region] = totals.get(region, 0.0) + units * unit_price
    return dict(sorted(totals.items()))


def main():
    rows = make_sales()
    totals = revenue_by_region(rows)
    for region, revenue in totals.items():
        print(f"{region:<6} {revenue:>10.2f}")
    print(f"{'total':<6} {sum(totals.values()):>10.2f}")


if __name__ == "__main__":
    main()

