[package]
name = "hickory-relay-server"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license.workspace = true

[[bin]]
name = "hickory-relay-server"
path = "src/main.rs"

[lib]
name = "hickory_relay_server"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
async-trait = "0.1"
axum = { version = "0.8", features = ["ws", "macros"] }
env_logger = "0.11"
futures = "0.3"
hickory-relay = { path = "../../crates/hickory-relay" }
log = "0.4"
reqwest = { version = "0.12", default-features = false, features = ["charset", "http2", "rustls-tls", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"

[dev-dependencies]
tokio-tungstenite = "0.24"
