//! Adopt a plain file into a literate document — byte-exact, or refused.
//!
//! Adoption is the first rung of the equivalence-preserving refactor ladder:
//! wrap an existing file's bytes verbatim in a `<hick:file>` block, and prove
//! (never assume) that weaving the new document reproduces the file exactly.
//! Only then does the document exist; from that moment the file is a
//! generated file with full lineage, editable in both directions, and every
//! later restructuring is checked against the same invariant by the refactor
//! baseline (`serve/refactor.rs`) and `hick equiv`.
//!
//! Two shapes:
//!
//! - **A new document beside the file** (`adopt_new`): verified in a scratch
//!   directory before anything is written into the working tree, so a
//!   failed adoption leaves no trace — and the in-app up-loop never sees a
//!   document whose weave would rewrite the user's file with wrong bytes.
//! - **A block appended to an existing document** (`adopt_into`): verified
//!   in place — the document's other inputs (pastes, upstream docs) live in
//!   the working tree — with an explicit restore of both the document and
//!   the file if the check fails.
//!
//! The refusals are the no-escaping invariant showing through: file content
//! goes into the block raw, so a file whose text contains a `hick:`-prefixed
//! tag cannot be wrapped verbatim. That is reported, not escaped around.

use std::path::{Path, PathBuf};

use anyhow::{Context as _, Result, bail};

use crate::{ExecutorChoice, RunMode, run_doc};

/// What an adoption produced.
pub struct AdoptOutcome {
    /// The document that now owns the file.
    pub doc_path: PathBuf,
    /// The `<hick:file path>` the block declares — the file's path relative
    /// to the DOCUMENT's directory, which is how the weave keys the output.
    pub output_path: String,
    /// True when the document was created; false when a block was appended.
    pub created: bool,
}

/// The document source wrapping `content` as the single output `rel`.
fn new_doc_source(rel: &str, content: &str) -> String {
    // Content starts immediately after the opening tag: putting the tag on
    // its own line would prepend a newline the file never had. A trailing
    // newline in the file keeps the closing tag on its own line for free.
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <hick:doc xmlns:hick=\"http://www.hickorydocs.com/1.0\">\n\
         # {name}\n\
         \n\
         Adopted from `{rel}` — the file below is now generated by this\n\
         document, byte-for-byte. Edit either side; the other follows.\n\
         \n\
         <hick:file path=\"{rel}\">{content}</hick:file>\n\
         </hick:doc>\n",
        name = rel.rsplit('/').next().unwrap_or(rel),
    )
}

/// The block `adopt_into` appends, same content convention as above.
fn file_block(rel: &str, content: &str) -> String {
    format!("\n<hick:file path=\"{rel}\">{content}</hick:file>\n")
}

/// Read the file to adopt, with the same honesty about what cannot be
/// adopted that the plain-file routes have about what cannot be edited.
fn read_adoptable(file: &Path) -> Result<String> {
    let bytes =
        std::fs::read(file).with_context(|| format!("could not read {}", file.display()))?;
    String::from_utf8(bytes).map_err(|_| {
        anyhow::anyhow!(
            "{} is not UTF-8 text — probably a binary file. A document \
             carries text; binary outputs are out of adoption's reach.",
            file.display()
        )
    })
}

/// Weave `doc` and return the produced text for output `rel`, or say what
/// went wrong in terms of the adoption rather than the pipeline.
async fn woven_output(doc: &Path, rel: &str) -> Result<String> {
    let run = run_doc(doc, &[], RunMode::Weave, ExecutorChoice::Local)
        .await
        .map_err(|e| {
            anyhow::anyhow!(
                "the adopted content does not survive being wrapped in a \
                 document ({e:#}). This usually means the file contains \
                 `hick:`-prefixed tags, which the parser treats as structure \
                 — the no-escaping invariant has no way to quote them."
            )
        })?;
    match run.result.files.get(rel) {
        Some(content) => content.as_text().map(str::to_string).ok_or_else(|| {
            anyhow::anyhow!("the woven {rel} came back as binary, which adoption never produces")
        }),
        None => bail!(
            "weaving the document produced no output named {rel} — the file \
             block did not take effect"
        ),
    }
}

/// The byte-exactness gate every adoption passes or dies on.
fn verify_bytes(rel: &str, original: &str, woven: &str) -> Result<()> {
    if woven == original {
        return Ok(());
    }
    // Find the first differing line so the refusal names WHERE, not just "no".
    let line = original
        .lines()
        .zip(woven.lines())
        .position(|(a, b)| a != b)
        .map(|i| i + 1)
        .unwrap_or_else(|| original.lines().count().min(woven.lines().count()) + 1);
    bail!(
        "adoption would not be byte-exact: the woven {rel} first differs from \
         the file at line {line} ({} bytes on disk, {} woven). Nothing was \
         changed. This usually means the file contains `hick:`-prefixed text \
         the parser reads as structure.",
        original.len(),
        woven.len(),
    )
}

/// Adopt `file` into a NEW document beside it: `<stem>.hick`.
///
/// The verification runs in a scratch directory first; the working tree is
/// only touched once the round-trip is proven byte-exact.
pub async fn adopt_new(file: &Path) -> Result<AdoptOutcome> {
    let content = read_adoptable(file)?;
    let name = file
        .file_name()
        .and_then(|n| n.to_str())
        .with_context(|| format!("{} has no usable file name", file.display()))?;
    if name.ends_with(".hick") {
        bail!("{name} is already a document — adoption is for the files documents do not own yet");
    }
    let stem = file.file_stem().and_then(|s| s.to_str()).unwrap_or(name);
    let doc_path = file.with_file_name(format!("{stem}.hick"));
    if doc_path.exists() {
        bail!(
            "{} already exists. Adopt into it instead (`hick adopt {} --into {}`), \
             or pick a different name for the new document.",
            doc_path.display(),
            file.display(),
            doc_path.display(),
        );
    }

    let source = new_doc_source(name, &content);

    // Prove the round-trip somewhere the up-loop is not watching: a failed
    // check must leave the working tree exactly as it was.
    let scratch = tempfile::tempdir().context("could not create a scratch directory")?;
    let scratch_doc = scratch.path().join("adopt.hick");
    std::fs::write(&scratch_doc, &source).context("could not write the scratch document")?;
    let woven = woven_output(&scratch_doc, name).await?;
    verify_bytes(name, &content, &woven)?;

    std::fs::write(&doc_path, &source)
        .with_context(|| format!("could not write {}", doc_path.display()))?;
    Ok(AdoptOutcome {
        doc_path,
        output_path: name.to_string(),
        created: true,
    })
}

/// Adopt `file` by appending a block to the EXISTING document `doc`.
///
/// Verified in place — the document's other blocks may read the working
/// tree — with both the document and the file restored if the check fails.
/// The equivalence obligation is wider here: every output the document
/// already produced must come out identical, and the new one must equal the
/// file. `hick:file` paths resolve against the document's directory, so the
/// file must live at or below it.
pub async fn adopt_into(file: &Path, doc: &Path) -> Result<AdoptOutcome> {
    let content = read_adoptable(file)?;
    let doc_dir = doc.parent().unwrap_or(Path::new("."));
    let rel = file
        .strip_prefix(doc_dir)
        .ok()
        .and_then(|p| p.to_str())
        .map(|p| p.replace('\\', "/"))
        .with_context(|| {
            format!(
                "{} does not live under {}'s directory — a document's file \
                 blocks name paths below it. Adopt into a document beside or \
                 above the file.",
                file.display(),
                doc.display(),
            )
        })?;

    let original_source = std::fs::read_to_string(doc)
        .with_context(|| format!("could not read {}", doc.display()))?;

    // The equivalence baseline: what the document produces today.
    let before = run_doc(doc, &[], RunMode::Weave, ExecutorChoice::Local)
        .await
        .map_err(|e| {
            anyhow::anyhow!(
                "{} does not weave as it stands ({e:#}) — fix that first; \
                 adoption must start from a document whose outputs are known",
                doc.display()
            )
        })?;
    if before.result.files.contains_key(&rel) {
        bail!(
            "{} already produces {rel} — it is a generated file, not a plain \
             one. Edit it through its document.",
            doc.display()
        );
    }

    let close = original_source.rfind("</hick:doc>").with_context(|| {
        format!(
            "{} has no closing </hick:doc> tag to append before",
            doc.display()
        )
    })?;
    let mut next_source = original_source.clone();
    next_source.insert_str(close, &file_block(&rel, &content));

    std::fs::write(doc, &next_source)
        .with_context(|| format!("could not write {}", doc.display()))?;

    // In-place check, with explicit restore on every failure path: the
    // up-loop may have woven the candidate meanwhile, so the FILE is
    // restored too, not just the document.
    let restore = |reason: anyhow::Error| -> anyhow::Error {
        let doc_back = std::fs::write(doc, &original_source);
        let file_back = std::fs::write(file, &content);
        match (doc_back, file_back) {
            (Ok(()), Ok(())) => reason,
            (d, f) => anyhow::anyhow!(
                "{reason:#}; AND restoring failed (doc: {d:?}, file: {f:?}) — \
                 check {} and {} by hand",
                doc.display(),
                file.display(),
            ),
        }
    };

    let after = match run_doc(doc, &[], RunMode::Weave, ExecutorChoice::Local).await {
        Ok(run) => run,
        Err(e) => {
            return Err(restore(anyhow::anyhow!(
                "the appended block does not weave: {e:#}"
            )));
        }
    };
    let woven = match after.result.files.get(&rel).and_then(|c| c.as_text()) {
        Some(text) => text.to_string(),
        None => {
            return Err(restore(anyhow::anyhow!(
                "weaving produced no output named {rel} — the appended block did not take effect"
            )));
        }
    };
    if let Err(e) = verify_bytes(&rel, &content, &woven) {
        return Err(restore(e));
    }
    // The wider obligation: nothing the document already produced may move.
    //
    // Its own woven markdown is the one exemption, and is not a loophole: that
    // file is the *rendering of the document we just appended to*, so it must
    // change — a document that grew a block and rendered identically would mean
    // the block did not take effect. The bytes this guarantee is actually about
    // are the adopted file's, checked by `verify_bytes` above, and every other
    // generated output, checked below.
    let own_weave = before.doc.weave_path.clone();
    for (path, was) in &before.result.files {
        if Some(path) == own_weave.as_ref() {
            continue;
        }
        let now = after.result.files.get(path);
        let unchanged = match (was.as_text(), now.and_then(|c| c.as_text())) {
            (Some(a), Some(b)) => a == b,
            _ => now.is_some(),
        };
        if !unchanged {
            return Err(restore(anyhow::anyhow!(
                "appending the block changed an existing output ({path}) — \
                 adoption must leave every other byte alone"
            )));
        }
    }

    Ok(AdoptOutcome {
        doc_path: doc.to_path_buf(),
        output_path: rel,
        created: false,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn block_on<T>(fut: impl std::future::Future<Output = T>) -> T {
        tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("runtime")
            .block_on(fut)
    }

    // Protects docs/guarantees/authoring/adoption-is-byte-exact-or-refused.md.
    #[test]
    fn adopting_a_file_creates_a_doc_whose_weave_is_byte_identical() {
        let dir = tempfile::tempdir().unwrap();
        let file = dir.path().join("analysis.py");
        let body = "import sys\n\nprint(sys.argv)\n";
        std::fs::write(&file, body).unwrap();

        let outcome = block_on(adopt_new(&file)).expect("adoption succeeds");
        assert!(outcome.created);
        assert_eq!(outcome.doc_path, dir.path().join("analysis.hick"));
        assert_eq!(
            std::fs::read_to_string(&file).unwrap(),
            body,
            "adoption changes no byte of the file"
        );
        let woven = block_on(woven_output(&outcome.doc_path, "analysis.py")).unwrap();
        assert_eq!(woven, body, "the document reproduces the file exactly");
    }

    #[test]
    fn a_file_without_a_trailing_newline_still_round_trips() {
        let dir = tempfile::tempdir().unwrap();
        let file = dir.path().join("fragment.txt");
        std::fs::write(&file, "no newline at end").unwrap();
        let outcome = block_on(adopt_new(&file)).expect("adoption succeeds");
        let woven = block_on(woven_output(&outcome.doc_path, "fragment.txt")).unwrap();
        assert_eq!(woven, "no newline at end");
    }

    #[test]
    fn a_file_containing_hick_tags_is_refused_and_nothing_is_written() {
        let dir = tempfile::tempdir().unwrap();
        let file = dir.path().join("notes.md");
        std::fs::write(&file, "docs about hick:\n</hick:file>\nboom\n").unwrap();
        let before = std::fs::read_dir(dir.path()).unwrap().count();
        assert!(
            block_on(adopt_new(&file)).is_err(),
            "structure-looking text is refused"
        );
        assert_eq!(
            std::fs::read_dir(dir.path()).unwrap().count(),
            before,
            "a refused adoption leaves no document behind"
        );
    }

    #[test]
    fn refuses_binaries_documents_and_a_taken_doc_name() {
        let dir = tempfile::tempdir().unwrap();
        let png = dir.path().join("logo.png");
        std::fs::write(&png, [0x89u8, 0x50, 0xff, 0x00]).unwrap();
        assert!(block_on(adopt_new(&png)).is_err());

        let doc = dir.path().join("paper.hick");
        std::fs::write(&doc, "<hick:doc/>").unwrap();
        assert!(
            block_on(adopt_new(&doc)).is_err(),
            "a document is not adoptable"
        );

        let file = dir.path().join("paper.txt");
        std::fs::write(&file, "text\n").unwrap();
        assert!(
            block_on(adopt_new(&file)).is_err(),
            "paper.hick exists; the refusal points at --into"
        );
    }

    #[test]
    fn adopt_into_appends_and_leaves_every_other_output_alone() {
        let dir = tempfile::tempdir().unwrap();
        let doc = dir.path().join("notebook.hick");
        std::fs::write(&doc, new_doc_source("first.txt", "the first file\n")).unwrap();
        let file = dir.path().join("second.txt");
        std::fs::write(&file, "the second file\n").unwrap();

        let outcome = block_on(adopt_into(&file, &doc)).expect("append succeeds");
        assert!(!outcome.created);
        let woven_first = block_on(woven_output(&doc, "first.txt")).unwrap();
        let woven_second = block_on(woven_output(&doc, "second.txt")).unwrap();
        assert_eq!(woven_first, "the first file\n");
        assert_eq!(woven_second, "the second file\n");
    }

    #[test]
    fn adopt_into_restores_both_sides_when_the_check_fails() {
        let dir = tempfile::tempdir().unwrap();
        let doc = dir.path().join("notebook.hick");
        let original_doc = new_doc_source("first.txt", "the first file\n");
        std::fs::write(&doc, &original_doc).unwrap();
        let file = dir.path().join("tricky.md");
        let tricky = "prose\n</hick:file>\nmore\n";
        std::fs::write(&file, tricky).unwrap();

        assert!(block_on(adopt_into(&file, &doc)).is_err());
        assert_eq!(
            std::fs::read_to_string(&doc).unwrap(),
            original_doc,
            "the document is restored"
        );
        assert_eq!(
            std::fs::read_to_string(&file).unwrap(),
            tricky,
            "the file is restored"
        );
    }

    #[test]
    fn adopt_into_refuses_a_path_the_document_already_produces() {
        let dir = tempfile::tempdir().unwrap();
        let doc = dir.path().join("notebook.hick");
        std::fs::write(&doc, new_doc_source("owned.txt", "woven\n")).unwrap();
        // The woven file exists on disk after a weave; simulate that.
        let file = dir.path().join("owned.txt");
        std::fs::write(&file, "woven\n").unwrap();
        assert!(block_on(adopt_into(&file, &doc)).is_err());
    }
}
