//! Emit the editor's language data from the server's routing table.
use hick_lsp::lang_detect::{extensions, highlight, known_language_ids};

fn main() {
    print!(
        r#"// GENERATED by `just codegen` from crates/hick-lsp/src/lang_detect.rs.
// Do not edit: run `just codegen` instead. `just check-codegen` fails on drift.
//
// The server's routing table is the only statement of which languages exist.
// `highlight` says whether a CodeMirror grammar is expected for the id; the
// binding itself lives in `../languages.ts`, and a test there fails if a
// language claims a grammar it has not bound.

"#
    );
    let ids = known_language_ids();
    println!("export type RoutedLanguageId =");
    for id in &ids {
        println!("  | \"{id}\"");
    }
    println!(";\n");
    println!("/** Every routed language id, sorted. */");
    println!("export const ROUTED_LANGUAGE_IDS: readonly RoutedLanguageId[] = [");
    for id in &ids {
        println!("  \"{id}\",");
    }
    println!("];\n");
    println!("/** File extension (lowercase, no dot) to language id. */");
    println!("export const EXTENSION_TO_LANGUAGE: Readonly<Record<string, RoutedLanguageId>> = {{");
    for (ext, id, _) in extensions() {
        println!("  \"{ext}\": \"{id}\",");
    }
    println!("}};\n");
    println!("/** Languages the editor is expected to draw with a grammar. */");
    println!("export const HIGHLIGHTED_LANGUAGES: readonly RoutedLanguageId[] = [");
    for id in &ids {
        if highlight(id).is_editor() {
            println!("  \"{id}\",");
        }
    }
    println!("];");
}
