//! AI agent instructions management.
//!
//! This module provides functionality for creating and managing AI agent
//! instruction files in the `.agents/` directory pattern. It embeds the
//! AGENTS.md content at compile time and provides commands to initialize
//! and validate agent configurations.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use chrono::Local;

/// Embedded AGENTS.md content, included at compile time.
pub const EMBEDDED_AGENTS_MD: &str = include_str!("../docs/AGENTS.md");

/// The version of the hick CLI, used in auto-generated headers.
const VERSION: &str = env!("CARGO_PKG_VERSION");

/// Configuration for agent initialization.
#[derive(Debug, Default)]
pub struct InitConfig {
    /// Project directory (defaults to current directory).
    pub project_dir: PathBuf,
    /// Skip creating agent files.
    pub no_agents: bool,
}

/// Configuration for agent validation.
#[derive(Debug, Default)]
pub struct ValidateConfig {
    /// Project directory (defaults to current directory).
    pub project_dir: PathBuf,
    /// Automatically fix issues.
    pub fix: bool,
}

/// Issues that can be detected during validation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ValidationIssue {
    /// The .agents/hick.md file doesn't exist.
    FileMissing,
    /// The content doesn't match the embedded version (ignoring header).
    ContentMismatch,
    /// No reference found in CLAUDE.md or AGENTS.md.
    ReferenceMissing,
}

impl std::fmt::Display for ValidationIssue {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ValidationIssue::FileMissing => {
                write!(f, ".agents/hick.md file is missing")
            }
            ValidationIssue::ContentMismatch => {
                write!(f, ".agents/hick.md content differs from embedded version")
            }
            ValidationIssue::ReferenceMissing => {
                write!(
                    f,
                    "no reference to .agents/hick.md found in CLAUDE.md or AGENTS.md"
                )
            }
        }
    }
}

/// Generate the auto-generated header for agent files.
fn generate_header() -> String {
    let timestamp = Local::now().format("%Y-%m-%d %H:%M:%S");
    format!(
        "<!-- AUTO-GENERATED by hick v{VERSION} at {timestamp} -->\n\
         <!-- Do not edit manually. Regenerate with: hick init -->\n\n"
    )
}

/// The reference line to add to CLAUDE.md or AGENTS.md.
const REFERENCE_LINE: &str = "See also: [.agents/hick.md](.agents/hick.md) for hick instructions.";

/// Check if a file contains a reference to .agents/hick.md.
fn has_hick_reference(content: &str) -> bool {
    content.contains(".agents/hick.md")
}

/// Find the instruction file to wire the reference into.
///
/// Priority: CLAUDE.md first, then AGENTS.md.
fn find_instruction_file(project_dir: &Path) -> Option<PathBuf> {
    let claude_md = project_dir.join("CLAUDE.md");
    if claude_md.is_file() {
        return Some(claude_md);
    }

    let agents_md = project_dir.join("AGENTS.md");
    if agents_md.is_file() {
        return Some(agents_md);
    }

    None
}

/// Extract content without the auto-generated header.
fn strip_header(content: &str) -> &str {
    // Look for the end of the header section (two consecutive newlines after comments)
    if content.starts_with("<!--") {
        // Find the blank line after the header comments
        if let Some(pos) = content.find("\n\n") {
            let after_first = &content[pos + 2..];
            if after_first.starts_with("<!--") {
                // Second comment line
                if let Some(pos2) = after_first.find("\n\n") {
                    return after_first[pos2 + 2..].trim_start();
                }
            }
            return after_first.trim_start();
        }
    }
    content
}

/// Initialize agent files for a project.
///
/// Creates `.agents/hick.md` with the embedded content and wires a reference
/// into CLAUDE.md or AGENTS.md if present.
pub fn init_agents(config: &InitConfig) -> Result<InitResult> {
    if config.no_agents {
        let pipeline_initialized = init_pipeline_config(&config.project_dir)?;
        return Ok(InitResult {
            agents_file_created: false,
            reference_added_to: None,
            pipeline_initialized,
        });
    }

    let agents_dir = config.project_dir.join(".agents");
    let agents_file = agents_dir.join("hick.md");

    // Create .agents directory
    fs::create_dir_all(&agents_dir)
        .with_context(|| format!("failed to create directory: {}", agents_dir.display()))?;

    // Write the agents file with header
    let content = format!("{}{}", generate_header(), EMBEDDED_AGENTS_MD);
    fs::write(&agents_file, &content)
        .with_context(|| format!("failed to write: {}", agents_file.display()))?;

    // Wire reference to instruction file
    let reference_added_to =
        if let Some(instruction_file) = find_instruction_file(&config.project_dir) {
            let existing = fs::read_to_string(&instruction_file)
                .with_context(|| format!("failed to read: {}", instruction_file.display()))?;

            if !has_hick_reference(&existing) {
                // Add reference at the end
                let updated = if existing.ends_with('\n') {
                    format!("{}\n{}\n", existing.trim_end(), REFERENCE_LINE)
                } else {
                    format!("{}\n\n{}\n", existing, REFERENCE_LINE)
                };
                fs::write(&instruction_file, updated)
                    .with_context(|| format!("failed to update: {}", instruction_file.display()))?;
                Some(instruction_file)
            } else {
                None // Already has reference
            }
        } else {
            None
        };

    // Auto-create _hick.yml if absent
    let pipeline_initialized = init_pipeline_config(&config.project_dir)?;

    Ok(InitResult {
        agents_file_created: true,
        reference_added_to,
        pipeline_initialized,
    })
}

/// Create a minimal `_hick.yml` in `project_dir` if one does not already exist.
///
/// Returns `true` if the file was created, `false` if it already existed.
fn init_pipeline_config(project_dir: &Path) -> Result<bool> {
    let config_path = project_dir.join("_hick.yml");
    if config_path.is_file() {
        return Ok(false);
    }
    let content = "# Hick pipeline root — list .hick source files in order\nfiles: []\n";
    fs::write(&config_path, content)
        .with_context(|| format!("failed to create: {}", config_path.display()))?;
    Ok(true)
}

/// Result of initialization.
#[derive(Debug)]
pub struct InitResult {
    /// Whether .agents/hick.md was created.
    pub agents_file_created: bool,
    /// Path to the file where reference was added (if any).
    pub reference_added_to: Option<PathBuf>,
    /// Whether _hick.yml was newly created.
    pub pipeline_initialized: bool,
}

/// Validate agent configuration for a project.
///
/// Checks that:
/// 1. `.agents/hick.md` exists
/// 2. Content matches the embedded version (ignoring auto-generated header)
/// 3. A reference exists in CLAUDE.md or AGENTS.md
pub fn validate_agents(config: &ValidateConfig) -> Result<Vec<ValidationIssue>> {
    let mut issues = Vec::new();

    let agents_file = config.project_dir.join(".agents/hick.md");

    // Check if file exists
    if !agents_file.is_file() {
        issues.push(ValidationIssue::FileMissing);
    } else {
        // Check content matches (ignoring header)
        let existing = fs::read_to_string(&agents_file)
            .with_context(|| format!("failed to read: {}", agents_file.display()))?;
        let existing_content = strip_header(&existing);
        let expected_content = EMBEDDED_AGENTS_MD.trim_start();

        if existing_content.trim() != expected_content.trim() {
            issues.push(ValidationIssue::ContentMismatch);
        }
    }

    // Check for reference in instruction files
    let has_reference = check_instruction_files_for_reference(&config.project_dir);
    if !has_reference {
        issues.push(ValidationIssue::ReferenceMissing);
    }

    // Fix issues if requested
    if config.fix && !issues.is_empty() {
        let init_config = InitConfig {
            project_dir: config.project_dir.clone(),
            no_agents: false,
        };
        init_agents(&init_config)?;
        // Re-validate to see what's fixed
        return validate_agents(&ValidateConfig {
            project_dir: config.project_dir.clone(),
            fix: false,
        });
    }

    Ok(issues)
}

/// Check if any instruction file contains a reference to .agents/hick.md.
fn check_instruction_files_for_reference(project_dir: &Path) -> bool {
    for filename in ["CLAUDE.md", "AGENTS.md"] {
        let path = project_dir.join(filename);
        if path.is_file()
            && let Ok(content) = fs::read_to_string(&path)
            && has_hick_reference(&content)
        {
            return true;
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    /// A directory unique to this call.
    ///
    /// Keyed on the process id alone, every test in this module shared one
    /// directory and wiped it on entry — so under the default parallel
    /// runner one test deleted another's tree mid-assertion and the suite
    /// failed a different, random subset each run. The counter is what makes
    /// them independent.
    fn temp_dir() -> PathBuf {
        static NEXT: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);
        let n = NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        let dir = std::env::temp_dir().join(format!("hick-agents-test-{}-{n}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn test_init_creates_agents_file() {
        let dir = temp_dir();
        let config = InitConfig {
            project_dir: dir.clone(),
            no_agents: false,
        };

        let result = init_agents(&config).unwrap();
        assert!(result.agents_file_created);

        let agents_file = dir.join(".agents/hick.md");
        assert!(agents_file.is_file());

        let content = fs::read_to_string(&agents_file).unwrap();
        assert!(content.contains("AUTO-GENERATED"));
        assert!(content.contains("# hick"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_init_wires_claude_md() {
        let dir = temp_dir();
        fs::write(dir.join("CLAUDE.md"), "# Project\n\nSome content.\n").unwrap();

        let config = InitConfig {
            project_dir: dir.clone(),
            no_agents: false,
        };

        let result = init_agents(&config).unwrap();
        assert!(result.agents_file_created);
        assert_eq!(result.reference_added_to, Some(dir.join("CLAUDE.md")));

        let claude_content = fs::read_to_string(dir.join("CLAUDE.md")).unwrap();
        assert!(claude_content.contains(".agents/hick.md"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_init_prefers_claude_md_over_agents_md() {
        let dir = temp_dir();
        fs::write(dir.join("CLAUDE.md"), "# Claude\n").unwrap();
        fs::write(dir.join("AGENTS.md"), "# Agents\n").unwrap();

        let config = InitConfig {
            project_dir: dir.clone(),
            no_agents: false,
        };

        let result = init_agents(&config).unwrap();
        assert_eq!(result.reference_added_to, Some(dir.join("CLAUDE.md")));

        // AGENTS.md should not be modified
        let agents_content = fs::read_to_string(dir.join("AGENTS.md")).unwrap();
        assert!(!agents_content.contains(".agents/hick.md"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_init_skips_existing_reference() {
        let dir = temp_dir();
        fs::write(
            dir.join("CLAUDE.md"),
            "# Project\n\nSee also: [.agents/hick.md](.agents/hick.md)\n",
        )
        .unwrap();

        let config = InitConfig {
            project_dir: dir.clone(),
            no_agents: false,
        };

        let result = init_agents(&config).unwrap();
        assert!(result.agents_file_created);
        assert!(result.reference_added_to.is_none()); // Already has reference

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_init_no_agents_flag() {
        let dir = temp_dir();
        let config = InitConfig {
            project_dir: dir.clone(),
            no_agents: true,
        };

        let result = init_agents(&config).unwrap();
        assert!(!result.agents_file_created);
        assert!(!dir.join(".agents/hick.md").exists());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_validate_detects_missing_file() {
        let dir = temp_dir();
        let config = ValidateConfig {
            project_dir: dir.clone(),
            fix: false,
        };

        let issues = validate_agents(&config).unwrap();
        assert!(issues.contains(&ValidationIssue::FileMissing));
        assert!(issues.contains(&ValidationIssue::ReferenceMissing));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_validate_detects_content_mismatch() {
        let dir = temp_dir();
        fs::create_dir_all(dir.join(".agents")).unwrap();
        fs::write(dir.join(".agents/hick.md"), "# Wrong content\n").unwrap();
        fs::write(
            dir.join("CLAUDE.md"),
            "See [.agents/hick.md](.agents/hick.md)\n",
        )
        .unwrap();

        let config = ValidateConfig {
            project_dir: dir.clone(),
            fix: false,
        };

        let issues = validate_agents(&config).unwrap();
        assert!(issues.contains(&ValidationIssue::ContentMismatch));
        assert!(!issues.contains(&ValidationIssue::FileMissing));
        assert!(!issues.contains(&ValidationIssue::ReferenceMissing));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_validate_passes_correct_setup() {
        let dir = temp_dir();

        // Initialize properly first
        let init_config = InitConfig {
            project_dir: dir.clone(),
            no_agents: false,
        };
        fs::write(dir.join("CLAUDE.md"), "# Project\n").unwrap();
        init_agents(&init_config).unwrap();

        // Validate
        let config = ValidateConfig {
            project_dir: dir.clone(),
            fix: false,
        };

        let issues = validate_agents(&config).unwrap();
        assert!(issues.is_empty(), "Expected no issues, got: {:?}", issues);

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_validate_fix_creates_missing_file() {
        let dir = temp_dir();
        fs::write(dir.join("CLAUDE.md"), "# Project\n").unwrap();

        let config = ValidateConfig {
            project_dir: dir.clone(),
            fix: true,
        };

        let issues = validate_agents(&config).unwrap();
        assert!(issues.is_empty(), "Fix should resolve all issues");
        assert!(dir.join(".agents/hick.md").is_file());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_strip_header() {
        let with_header = "<!-- AUTO-GENERATED by hick v0.1.0 at 2024-01-01 12:00:00 -->\n\
                           <!-- Do not edit manually. Regenerate with: hick init -->\n\n\
                           # hick\n\nContent here.";
        let stripped = strip_header(with_header);
        assert_eq!(stripped, "# hick\n\nContent here.");

        let without_header = "# hick\n\nContent here.";
        let stripped2 = strip_header(without_header);
        assert_eq!(stripped2, without_header);
    }

    #[test]
    fn test_generate_header_format() {
        let header = generate_header();
        assert!(header.starts_with("<!-- AUTO-GENERATED by hick v"));
        assert!(header.contains("Do not edit manually"));
        assert!(header.contains("hick init"));
    }

    #[test]
    fn test_embedded_content_not_empty() {
        assert!(!EMBEDDED_AGENTS_MD.is_empty());
        assert!(EMBEDDED_AGENTS_MD.contains("# hick"));
    }
}
