//! Stale output file cleanup.
//!
//! After writing pipeline outputs, removes files and empty directories
//! from the output directory that are no longer produced by the pipeline.

use std::collections::HashSet;
use std::path::{Path, PathBuf};

use anyhow::Result;
use log::info;

/// Remove files and directories from `output_dir` that are not in `expected_paths`.
///
/// This is called after writing output files to clean up stale artifacts from
/// previous runs. Only operates when `output_dir` is a non-trivial path (not ".").
///
/// Only cleans files in directories that hick is actively writing to (i.e.,
/// directories that contain at least one expected file). This prevents deletion
/// of files generated by other tools (like xcodegen) in sibling directories.
///
/// `expected_paths` should contain paths relative to `output_dir`.
pub fn clean_stale_outputs(output_dir: &Path, expected_paths: &HashSet<PathBuf>) -> Result<()> {
    if output_dir == Path::new(".") || !output_dir.exists() {
        return Ok(());
    }

    // Build set of "managed directories" - directories that directly contain expected files
    let managed_dirs: HashSet<PathBuf> = expected_paths
        .iter()
        .filter_map(|p| p.parent().map(|parent| parent.to_path_buf()))
        .collect();

    // Collect all files currently in the output directory
    let mut stale_files: Vec<PathBuf> = Vec::new();
    let mut stale_dirs: Vec<PathBuf> = Vec::new();

    collect_files_recursive(
        output_dir,
        output_dir,
        &mut stale_files,
        expected_paths,
        &managed_dirs,
    )?;

    // Delete stale files
    for file in &stale_files {
        info!("Removing stale output: {}", file.display());
        if let Err(e) = std::fs::remove_file(file) {
            log::warn!("Failed to remove stale file {}: {}", file.display(), e);
        }
    }

    // Collect empty directories after file deletion
    collect_empty_dirs_recursive(output_dir, &mut stale_dirs)?;

    // Delete empty directories (deepest first)
    stale_dirs.sort_by_key(|b| std::cmp::Reverse(b.components().count()));
    for dir in &stale_dirs {
        // Double-check it's still empty and within output_dir
        if dir.starts_with(output_dir)
            && dir != output_dir
            && dir.is_dir()
            && std::fs::read_dir(dir)
                .map(|mut d| d.next().is_none())
                .unwrap_or(false)
        {
            info!("Removing empty directory: {}", dir.display());
            if let Err(e) = std::fs::remove_dir(dir) {
                log::warn!("Failed to remove empty directory {}: {}", dir.display(), e);
            }
        }
    }

    if !stale_files.is_empty() || !stale_dirs.is_empty() {
        info!(
            "Cleaned {} stale file(s) and {} empty director{}",
            stale_files.len(),
            stale_dirs.len(),
            if stale_dirs.len() == 1 { "y" } else { "ies" }
        );
    }

    Ok(())
}

/// Recursively collect files that are not in the expected set.
///
/// Only considers files in "managed directories" - directories that contain
/// at least one expected file. This prevents cleaning files in directories
/// that hick doesn't write to (e.g., xcodegen-generated .xcodeproj).
fn collect_files_recursive(
    dir: &Path,
    base: &Path,
    stale: &mut Vec<PathBuf>,
    expected: &HashSet<PathBuf>,
    managed_dirs: &HashSet<PathBuf>,
) -> Result<()> {
    if !dir.is_dir() {
        return Ok(());
    }

    // Get directory path relative to base
    let rel_dir = dir.strip_prefix(base).unwrap_or(Path::new(""));

    // Only process this directory if it's a managed directory
    let is_managed = rel_dir.as_os_str().is_empty() || managed_dirs.contains(rel_dir);

    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.is_dir() {
            collect_files_recursive(&path, base, stale, expected, managed_dirs)?;
        } else if path.is_file() && is_managed {
            // Only consider files in managed directories
            if let Ok(rel) = path.strip_prefix(base)
                && !expected.contains(rel)
            {
                stale.push(path);
            }
        }
    }

    Ok(())
}

/// Recursively collect empty directories.
fn collect_empty_dirs_recursive(dir: &Path, empty_dirs: &mut Vec<PathBuf>) -> Result<bool> {
    if !dir.is_dir() {
        return Ok(false);
    }

    let mut has_content = false;
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.is_dir() {
            let subdir_empty = collect_empty_dirs_recursive(&path, empty_dirs)?;
            if !subdir_empty {
                has_content = true;
            }
        } else {
            has_content = true;
        }
    }

    if !has_content {
        empty_dirs.push(dir.to_path_buf());
    }

    Ok(!has_content)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clean_stale_outputs_removes_extra_files() {
        let dir = std::env::temp_dir().join("hick-clean-stale-test");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();

        // Create some files: one expected, one stale
        std::fs::write(dir.join("expected.txt"), "keep").unwrap();
        std::fs::write(dir.join("stale.txt"), "remove").unwrap();

        let mut expected = HashSet::new();
        expected.insert(PathBuf::from("expected.txt"));

        clean_stale_outputs(&dir, &expected).unwrap();

        // Expected file should still exist
        assert!(dir.join("expected.txt").exists());
        // Stale file should be removed
        assert!(!dir.join("stale.txt").exists());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn clean_stale_outputs_removes_empty_dirs() {
        let dir = std::env::temp_dir().join("hick-clean-dirs-test");
        let _ = std::fs::remove_dir_all(&dir);

        // Create nested structure: output/subdir/file.txt and output/empty/
        std::fs::create_dir_all(dir.join("subdir")).unwrap();
        std::fs::create_dir_all(dir.join("empty")).unwrap();
        std::fs::write(dir.join("subdir").join("file.txt"), "keep").unwrap();

        let mut expected = HashSet::new();
        expected.insert(PathBuf::from("subdir/file.txt"));

        clean_stale_outputs(&dir, &expected).unwrap();

        // Subdir and file should still exist
        assert!(dir.join("subdir").join("file.txt").exists());
        // Empty dir should be removed
        assert!(!dir.join("empty").exists());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn clean_stale_outputs_only_cleans_managed_dirs() {
        let dir = std::env::temp_dir().join("hick-clean-managed-test");
        let _ = std::fs::remove_dir_all(&dir);

        // Simulate xcodegen scenario:
        // - hick writes to apple/MyProject/ContentView.swift
        // - xcodegen creates apple/MyProject.xcodeproj/project.pbxproj
        // The xcodeproj should NOT be cleaned because hick doesn't write there
        std::fs::create_dir_all(dir.join("apple/MyProject")).unwrap();
        std::fs::create_dir_all(dir.join("apple/MyProject.xcodeproj")).unwrap();
        std::fs::write(dir.join("apple/MyProject/ContentView.swift"), "keep").unwrap();
        std::fs::write(dir.join("apple/MyProject/OldFile.swift"), "stale").unwrap();
        std::fs::write(
            dir.join("apple/MyProject.xcodeproj/project.pbxproj"),
            "xcodegen",
        )
        .unwrap();

        let mut expected = HashSet::new();
        expected.insert(PathBuf::from("apple/MyProject/ContentView.swift"));

        clean_stale_outputs(&dir, &expected).unwrap();

        // Expected file should exist
        assert!(dir.join("apple/MyProject/ContentView.swift").exists());
        // Stale file in same directory should be removed
        assert!(!dir.join("apple/MyProject/OldFile.swift").exists());
        // xcodegen file should NOT be removed (different directory, not managed by hick)
        assert!(
            dir.join("apple/MyProject.xcodeproj/project.pbxproj")
                .exists()
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn clean_stale_outputs_cleans_stale_in_same_dir() {
        let dir = std::env::temp_dir().join("hick-clean-same-dir-test");
        let _ = std::fs::remove_dir_all(&dir);

        // Create: output/src/keep.txt and output/src/stale.txt
        std::fs::create_dir_all(dir.join("src")).unwrap();
        std::fs::write(dir.join("src").join("keep.txt"), "keep").unwrap();
        std::fs::write(dir.join("src").join("stale.txt"), "remove").unwrap();

        let mut expected = HashSet::new();
        expected.insert(PathBuf::from("src/keep.txt"));

        clean_stale_outputs(&dir, &expected).unwrap();

        // Keep file should exist
        assert!(dir.join("src").join("keep.txt").exists());
        // Stale file in same directory should be removed
        assert!(!dir.join("src").join("stale.txt").exists());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn clean_stale_outputs_noop_for_current_dir() {
        // Should not do anything when output_dir is "."
        let expected = HashSet::new();
        clean_stale_outputs(Path::new("."), &expected).unwrap();
        // No assertions needed - just ensure it doesn't panic or delete anything
    }

    #[test]
    fn clean_stale_outputs_noop_for_nonexistent_dir() {
        let dir = std::env::temp_dir().join("hick-clean-nonexistent-test");
        let _ = std::fs::remove_dir_all(&dir);
        // Don't create the directory

        let expected = HashSet::new();
        clean_stale_outputs(&dir, &expected).unwrap();
        // Should not panic
    }
}
